#!/usr/bin/env python3
"""Generate 七年级下册词汇表.md from OCR-extracted vocabulary."""
import os

BASE = '/Users/allen/Downloads/人教版(PEP)'

C1B_VOCAB = [
    # ===== A =====
    ("a few", "/ə 'fjuː/", "一些；几个", "47", False),
    ("absent", "/'æbsənt/", "adj. 缺席的；不在的", "13", False),
    ("absent from", "", "缺席；未参加", "13", False),
    ("actor", "/'æktə(r)/", "n. 演员", "53", False),
    ("advice", "/əd'vaɪs/", "n. 建议；忠告", "15", False),
    ("affect", "/ə'fekt/", "v. 影响", "41", False),
    ("afraid", "/ə'freɪd/", "adj. 害怕的；担心的", "59", False),
    ("after all", "", "毕竟；终究", "30", False),
    ("agree", "/ə'ɡriː/", "v. 同意；赞成", "55", False),
    ("agree with", "", "同意；赞成", "55", False),
    ("all over", "", "到处；遍及", "61", False),
    ("along", "/ə'lɒŋ/", "prep. 沿着；顺着", "53", False),
    ("although", "/ɔːl'ðəʊ/", "conj. 虽然；尽管", "45", False),
    ("among", "/ə'mʌŋ/", "prep. 在……之中", "31", False),
    ("anyone", "/'eniwʌn/", "pron. 任何人", "21", False),
    ("anything", "/'eniθɪŋ/", "pron. 任何事物；任何东西", "27", False),
    ("app", "/æp/", "n. (=application) 应用程序", "22", False),
    ("area", "/'eəriə/", "n. 地区；区域", "46", False),
    ("around the world", "", "全世界", "38", False),
    ("arrive", "/ə'raɪv/", "v. 到达", "10", False),
    ("article", "/'ɑːtɪkl/", "n. 文章；冠词", "31", False),
    ("artist", "/'ɑːtɪst/", "n. 艺术家；画家", "61", False),
    ("at first", "", "起初；最初", "60", False),
    ("at the end", "", "最后；结尾", "47", False),
    ("at the moment", "", "此刻；目前", "34", False),
    ("at the start", "", "开始；起初", "46", False),
    ("at the top", "", "在顶部；在顶端", "46", False),
    ("away", "/ə'weɪ/", "adv. 离开；远离", "30", False),
    ("awful", "/'ɔːfl/", "adj. 糟糕的；讨厌的", "14", False),

    # ===== B =====
    ("badminton", "/'bædmɪntən/", "n. 羽毛球运动", "19", False),
    ("balanced", "/'bælənst/", "adj. 均衡的；平衡的", "30", False),
    ("baseball", "/'beɪsbɔːl/", "n. 棒球运动", "18", False),
    ("basket", "/'bɑːskɪt/", "n. 篮子；筐", "54", False),
    ("beach volleyball", "", "沙滩排球", "46", False),
    ("bean", "/biːn/", "n. 豆", "26", False),
    ("because of", "", "因为", "31", False),
    ("become", "/bɪ'kʌm/", "v. (became; become) 变成；成为", "14", False),
    ("belong", "/bɪ'lɒŋ/", "v. 属于", "21", False),
    ("belong to", "", "属于", "21", False),
    ("belt", "/belt/", "n. 腰带；皮带", "13", False),
    ("better", "/'betə(r)/", "adj. 更好的 adv. 更好地", "14", False),
    ("bill", "/bɪl/", "n. 账单；法案", "29", False),
    ("bite", "/baɪt/", "v. (bit) 咬；叮", "58", False),
    ("bite through", "", "咬穿", "58", False),
    ("blind", "/blaɪnd/", "adj. 瞎的；盲的", "7", False),
    ("branch", "/brɑːntʃ/", "n. 树枝；分支", "54", False),
    ("bright", "/braɪt/", "adj. 明亮的；聪明的", "38", False),
    ("brightly", "/'braɪtli/", "adv. 明亮地", "38", False),
    ("build", "/bɪld/", "v. (built) 建造；修建", "14", False),

    # ===== C =====
    ("cabbage", "/'kæbɪdʒ/", "n. 卷心菜", "26", False),
    ("call back", "", "回电话", "36", False),
    ("care", "/keə(r)/", "n. 关心；照顾 v. 在乎", "19", False),
    ("carry", "/'kæri/", "v. 搬；携带", "6", False),
    ("cause", "/kɔːz/", "v. 引起；导致", "35", False),
    ("central", "/'sentrəl/", "adj. 中心的；中央的", "38", False),
    ("certainly", "/'sɜːtnli/", "adv. 当然；必定", "54", False),
    ("chip", "/tʃɪp/", "n. 炸薯条；芯片", "26", False),
    ("choice", "/tʃɔɪs/", "n. 选择", "28", False),
    ("cloud", "/klaʊd/", "n. 云；云状物", "46", False),
    ("coffee", "/'kɒfi/", "n. 咖啡", "26", False),
    ("colourful", "/'kʌləfl/", "adj. 色彩鲜艳的", "38", False),
    ("come out", "", "出来；出版；开花", "63", False),
    ("common", "/'kɒmən/", "adj. 普通的；共同的", "31", False),
    ("cookie", "/'kʊki/", "n. 曲奇饼", "26", False),
    ("could", "/kʊd; kəd/", "modal v. 可以；能", "36", False),
    ("create", "/kri'eɪt/", "v. 创造；创建", "53", False),
    ("cucumber", "/'kjuːkʌmbə(r)/", "n. 黄瓜", "26", False),
    ("culture", "/'kʌltʃə(r)/", "n. 文化；文明", "54", False),
    ("customer", "/'kʌstəmə(r)/", "n. 顾客", "29", False),
    ("cut down", "", "砍倒；减少", "21", False),

    # ===== D =====
    ("danger", "/'deɪndʒə(r)/", "n. 危险", "6", False),
    ("dangerous", "/'deɪndʒərəs/", "adj. 危险的", "5", False),
    ("darling", "/'dɑːlɪŋ/", "n. 亲爱的", "35", False),
    ("decide", "/dɪ'saɪd/", "v. 决定", "59", False),
    ("description", "/dɪ'skrɪpʃn/", "n. 描述；说明", "47", False),
    ("diary", "/'daɪəri/", "n. 日记", "55", False),
    ("die", "/daɪ/", "v. 死；死亡", "63", False),
    ("direction", "/dɪ'rekʃn; daɪ'rekʃn/", "n. 方向", "50", False),
    ("dish", "/dɪʃ/", "n. 一道菜；盘子", "27", False),
    ("double", "/'dʌbl/", "n. 双打 adj. 双倍的", "18", False),
    ("Dr", "/'dɒktə(r)/", "n. (=doctor) 医生；博士", "14", False),
    ("dragon", "/'dræɡən/", "n. 龙", "30", False),
    ("drive", "/draɪv/", "v. (drove; driven) 驾驶；开车", "39", False),
    ("drop", "/drɒp/", "v. 落下；掉下 n. 滴", "38", False),
    ("drop off", "", "(开车)把某人送下", "38", False),
    ("dry", "/draɪ/", "adj. 干的；干燥的", "42", False),
    ("duckling", "/'dʌklɪŋ/", "n. 小鸭", "62", False),
    ("dumpling", "/'dʌmplɪŋ/", "n. 饺子", "26", False),

    # ===== E =====
    ("eagle", "/'iːɡl/", "n. 鹰", "2", False),
    ("east", "/iːst/", "n. 东方；东部 adj. 东方的", "42", False),
    ("either", "/'aɪðə(r); 'iːðə(r)/", "adv. 也(用于否定句)", "14", False),
    ("emperor", "/'empərə(r)/", "n. 皇帝", "59", False),
    ("encourage", "/ɪn'kʌrɪdʒ/", "v. 鼓励；激励", "6", False),
    ("end", "/end/", "n. 结尾；末端", "47", False),
    ("energy", "/'enədʒi/", "n. 能量；精力", "6", False),
    ("enough", "/ɪ'nʌf/", "adj. 足够的 adv. 足够地 pron. 足够", "31", False),
    ("entry", "/'entri/", "n. 条目；进入", "55", False),
    ("ever", "/'evə(r)/", "adv. 曾经；在任何时候", "18", False),
    ("everything", "/'evriθɪŋ/", "pron. 一切；所有事物", "11", False),
    ("exam", "/ɪɡ'zæm/", "n. (=examination) 考试", "55", False),
    ("excuse", "/ɪk'skjuːz/", "v. 原谅；宽恕", "20", False),
    ("excuse me", "", "打扰一下；对不起", "20", False),
    ("exhibition", "/ˌeksɪ'bɪʃn/", "n. 展览", "50", False),
    ("experience", "/ɪk'spɪəriəns/", "n. 经历；经验 v. 经历", "46", False),
    ("explain", "/ɪk'spleɪn/", "v. 解释；说明", "39", False),
    ("explore", "/ɪk'splɔː(r)/", "v. 探索", "54", False),

    # ===== F =====
    ("factory", "/'fæktri; 'fæktəri/", "n. 工厂", "51", False),
    ("fast food", "", "快餐", "30", False),
    ("fat", "/fæt/", "n. 脂肪 adj. 肥胖的", "30", False),
    ("feather", "/'feðə(r)/", "n. 羽毛", "62", False),
    ("feed", "/fiːd/", "v. (fed) 喂养；饲养", "18", False),
    ("feel like", "", "想要；感觉像", "46", False),
    ("festival", "/'festɪvl/", "n. 节日", "35", False),
    ("few", "/fjuː/", "adj. 很少的；少数的", "20", False),
    ("fill", "/fɪl/", "v. 装满；填充", "54", False),
    ("finally", "/'faɪnəli/", "adv. 最后；终于", "54", False),
    ("fish and chips", "", "炸鱼薯条", "26", False),
    ("fisherman", "/'fɪʃəmən/", "n. (pl. fishermen) 渔民", "63", False),
    ("fishing", "/'fɪʃɪŋ/", "n. 钓鱼", "63", False),
    ("fit", "/fɪt/", "adj. 健康的；合适的 v. 适合", "17", False),
    ("focus", "/'fəʊkəs/", "v. 集中(注意力)", "14", False),
    ("focus on", "", "集中于", "14", False),
    ("fog", "/fɒɡ/", "n. 雾", "46", False),
    ("follow", "/'fɒləʊ/", "v. 跟随；遵循", "10", False),
    ("forest", "/'fɒrɪst/", "n. 森林", "6", False),
    ("forward", "/'fɔːwəd/", "adv. 向前", "38", False),
    ("fox", "/fɒks/", "n. 狐狸", "2", False),
    ("freezing", "/'friːzɪŋ/", "adj. 极冷的；冰冻的", "45", False),
    ("fresh", "/freʃ/", "adj. 新鲜的", "54", False),
    ("friendly", "/'frendli/", "adj. 友好的", "7", False),
    ("from ... to ...", "", "从……到……", "54", False),
    ("full of", "", "充满", "21", False),
    ("fur", "/fɜː(r)/", "n. （动物的）毛皮", "7", False),

    # ===== G =====
    ("genie", "/'dʒiːni/", "n. 精灵；妖怪", "63", False),
    ("germ", "/dʒɜːm/", "n. 细菌；病菌", "52", False),
    ("get out", "", "出去；离开", "61", False),
    ("giraffe", "/dʒɪ'rɑːf/", "n. 长颈鹿", "30", False),
    ("glad", "/ɡlæd/", "adj. 高兴的；乐意的", "46", False),
    ("glove", "/ɡlʌv/", "n. (分指的)手套", "13", False),
    ("go away", "", "离开", "62", False),
    ("go on a trip", "", "去旅行", "52", False),
    ("go with", "", "与……相配；伴随", "29", False),
    ("goal", "/ɡəʊl/", "n. 目标；球门", "22", False),
    ("grain", "/ɡreɪn/", "n. 谷物；粮食", "54", False),
    ("grey", "/ɡreɪ/", "adj. (AmE gray) 灰色的", "46", False),
    ("ground", "/ɡraʊnd/", "n. 地面；场地", "46", False),
    ("group", "/ɡruːp/", "n. 组；群", "21", False),
    ("guess", "/ɡes/", "v. 猜测；估计", "5", False),
    ("gun", "/ɡʌn/", "n. 枪", "53", False),

    # ===== H =====
    ("habit", "/'hæbɪt/", "n. 习惯", "14", False),
    ("hallway", "/'hɔːlweɪ/", "n. 走廊；过道", "10", False),
    ("hamburger", "/'hæmbɜːɡə(r)/", "n. 汉堡包", "30", False),
    ("hang", "/hæŋ/", "v. (hung) 悬挂；吊着", "14", False),
    ("hang out", "", "闲逛；常去某处", "14", False),
    ("happen", "/'hæpən/", "v. 发生", "37", False),
    ("hardly", "/'hɑːdli/", "adv. 几乎不；简直不", "18", False),
    ("hardly ever", "", "几乎从不", "18", False),
    ("hate", "/heɪt/", "v. 讨厌；憎恨", "60", False),
    ("have to", "", "不得不", "10", False),
    ("hearing", "/'hɪərɪŋ/", "n. 听力；听觉", "20", False),
    ("heart", "/hɑːt/", "n. 心脏；内心", "7", False),
    ("heavily", "/'hevɪli/", "adv. 大量地；沉重地", "44", False),
    ("hen", "/hen/", "n. 母鸡", "62", False),
    ("hers", "/hɜːz; ɜːz/", "pron. 她的（名词性物主代词）", "19", False),
    ("high", "/haɪ/", "adv. 高 adj. 高的", "45", False),
    ("himself", "/hɪm'self/", "pron. 他自己", "37", False),
    ("hold", "/həʊld/", "v. (held) 拿着；握住", "63", False),
    ("hold on", "", "等一下；坚持", "35", False),
    ("hope", "/həʊp/", "v. & n. 希望", "35", False),
    ("hopefully", "/'həʊpfəli/", "adv. 有希望地", "62", False),
    ("however", "/haʊ'evə(r)/", "adv. 然而；不过", "6", False),
    ("huge", "/hjuːdʒ/", "adj. 巨大的；庞大的", "5", False),
    ("hunter", "/'hʌntə(r)/", "n. 猎人", "58", False),

    # ===== I =====
    ("if", "/ɪf/", "conj. 如果", "13", False),
    ("improve", "/ɪm'pruːv/", "v. 改善；提高", "30", False),
    ("in a hurry", "", "匆忙地", "11", False),
    ("in danger", "", "在危险中", "38", False),
    ("in high spirits", "", "情绪高涨；兴高采烈", "6", False),
    ("in the end", "", "最终；最后", "10", False),
    ("inside", "/ɪn'saɪd/", "prep. 在……里面 adv. 在里面", "63", False),
    ("instead", "/ɪn'sted/", "adv. 代替；反而", "52", False),
    ("instead of", "", "代替；而不是", "29", False),
    ("into", "/'ɪntuː; 'ɪntə/", "prep. 进入……里面", "51", False),
    ("ivory", "/'aɪvəri/", "n. 象牙", "6", False),

    # ===== J =====
    ("jacket", "/'dʒækɪt/", "n. 夹克衫；短上衣", "10", False),
    ("jog", "/dʒɒɡ/", "v. 慢跑", "30", False),
    ("jump rope", "", "跳绳", "30", False),
    ("jump the queue", "", "插队", "18", False),
    ("just", "/dʒʌst/", "adv. 只是；恰好", "21", False),

    # ===== K =====
    ("kick", "/kɪk/", "v. 踢", "37", False),
    ("kill", "/kɪl/", "v. 杀死；致死", "6", False),
    ("king", "/kɪŋ/", "n. 国王", "61", False),

    # ===== L =====
    ("late for", "", "迟到", "10", False),
    ("laugh at", "", "嘲笑", "5", False),
    ("lay", "/leɪ/", "v. (laid) 放置；产(卵)", "62", False),
    ("leaf", "/liːf/", "n. (pl. leaves) 叶子；树叶", "54", False),
    ("leave", "/liːv/", "v. (left) 离开；出发", "10", False),
    ("leave a message", "", "留言", "36", False),
    ("lend", "/lend/", "v. (lent) 借出；借给", "38", False),
    ("lie", "/laɪ/", "v. (lay; lain) 躺 n. 谎言", "59", False),
    ("lightning", "/'laɪtnɪŋ/", "n. 闪电", "46", False),
    ("litter", "/'lɪtə(r)/", "v. 乱扔 n. 垃圾", "10", False),
    ("long ago", "", "很久以前", "58", False),
    ("look after", "", "照顾；照料", "6", False),
    ("look forward to", "", "期待；盼望", "37", False),
    ("lose", "/luːz/", "v. (lost) 丢失；失去", "63", False),
    ("luck", "/lʌk/", "n. 运气；幸运", "6", False),
    ("lucky", "/'lʌki/", "adj. 幸运的；运气好的", "51", False),
    ("lucky you", "", "你真幸运", "43", False),

    # ===== M =====
    ("machine", "/mə'ʃiːn/", "n. 机器", "51", False),
    ("made of", "", "由……制成", "6", False),
    ("magical", "/'mædʒɪkl/", "adj. 有魔力的；神奇的", "46", False),
    ("make a promise", "", "许下诺言", "63", False),
    ("make money", "", "赚钱", "60", False),
    ("make progress", "", "取得进步", "46", False),
    ("make sb's/the bed", "", "整理床铺", "14", False),
    ("market", "/'mɑːkɪt/", "n. 市场", "38", False),
    ("mat", "/mæt/", "n. 垫子", "18", False),
    ("match", "/mætʃ/", "n. 比赛；火柴", "22", False),
    ("maybe", "/'meɪbi/", "adv. 也许；可能", "19", False),
    ("meal", "/miːl/", "n. 一餐；一顿饭", "28", False),
    ("meet up", "", "碰面；相聚", "50", False),
    ("menu", "/'menjuː/", "n. 菜单", "28", False),
    ("message", "/'mesɪdʒ/", "n. 消息；信息", "36", False),
    ("mine", "/maɪn/", "pron. 我的（名词性物主代词）", "19", False),
    ("mobile", "/'məʊbaɪl/", "adj. 移动的", "11", False),
    ("mobile phone", "", "手机", "11", False),
    ("moment", "/'məʊmənt/", "n. 时刻；片刻", "34", False),
    ("mount", "/maʊnt/", "n. （用于山名前）山；峰", "38", False),
    ("mountain", "/'maʊntɪn/", "n. 山；山脉", "47", False),
    ("museum", "/mju'ziːəm/", "n. 博物馆", "50", False),
    ("mutton", "/'mʌtn/", "n. 羊肉", "26", False),

    # ===== N =====
    ("neck", "/nek/", "n. 脖子", "5", False),
    ("neighbour", "/'neɪbə(r)/", "n. 邻居", "58", False),
    ("net", "/net/", "n. 网；网络", "58", False),
    ("newsletter", "/'njuːzletə(r)/", "n. 简报；通讯", "30", False),
    ("noise", "/nɔɪz/", "n. 噪音；吵闹声", "13", False),
    ("north", "/nɔːθ/", "n. 北方；北部 adj. 北方的", "42", False),
    ("not ... at all", "", "一点也不；根本不", "7", False),

    # ===== O =====
    ("of course", "/kɔːs/", "当然", "11", False),
    ("official", "/ə'fɪʃl/", "n. 官员；裁判 adj. 官方的", "59", False),
    ("on time", "", "准时", "10", False),
    ("once", "/wʌns/", "adv. 一次；曾经 conj. 一旦", "18", False),
    ("once upon a time", "", "从前；很久以前", "57", False),
    ("one another", "", "互相", "6", False),
    ("onion", "/'ʌnjən/", "n. 洋葱", "26", False),
    ("online", "/ˌɒn'laɪn/", "adj. 在线的", "37", False),
    ("only if", "", "只有当", "63", False),
    ("order", "/'ɔːdə(r)/", "n. 顺序；订单 v. 点菜；命令", "9", False),
    ("ours", "/'aʊəz; ɑːz/", "pron. 我们的（名词性物主代词）", "20", False),
    ("over there", "", "在那边", "21", False),

    # ===== P =====
    ("painting", "/'peɪntɪŋ/", "n. 绘画；油画", "46", False),
    ("passenger", "/'pæsɪndʒə(r)/", "n. 乘客", "38", False),
    ("peak", "/piːk/", "n. 山峰；顶峰", "46", False),
    ("pear", "/peə(r)/", "n. 梨", "29", False),
    ("penguin", "/'peŋɡwɪn/", "n. 企鹅", "2", False),
    ("perfect", "/'pɜːfɪkt/", "adj. 完美的；极好的", "19", False),
    ("person", "/'pɜːsn/", "n. 人", "14", False),
    ("pick", "/pɪk/", "v. 挑选；采摘", "6", False),
    ("pick up", "", "拿起；捡起；接(某人)", "6", False),
    ("piece", "/piːs/", "n. 片；块；件", "51", False),
    ("plant", "/plɑːnt/", "n. 植物 v. 种植", "51", False),
    ("playful", "/'pleɪfl/", "adj. 爱玩的；有趣的", "6", False),
    ("polite", "/pə'laɪt/", "adj. 有礼貌的", "10", False),
    ("poor", "/pɔː(r); pʊə(r)/", "adj. 贫穷的；可怜的", "31", False),
    ("pork", "/pɔːk/", "n. 猪肉", "28", False),
    ("porridge", "/'pɒrɪdʒ/", "n. 粥；麦片粥", "26", False),
    ("pour", "/pɔː(r)/", "v. 倒出；倾倒", "47", False),
    ("powerful", "/'paʊəfl/", "adj. 强大的；有力的", "63", False),
    ("practice", "/'præktɪs/", "n. 练习；实践", "19", False),
    ("practise", "/'præktɪs/", "v. 练习；训练", "14", False),
    ("praise", "/preɪz/", "v. & n. 赞扬；表扬", "59", False),
    ("pretend", "/prɪ'tend/", "v. 假装；装作", "59", False),
    ("process", "/'prəʊses/", "n. 过程", "52", False),
    ("progress", "/'prəʊɡres/", "n. 进步；进展", "22", False),
    ("promise", "/'prɒmɪs/", "v. 承诺；答应 n. 诺言", "58", False),
    ("purr", "/pɜː(r)/", "v. （猫）发出咕噜声", "62", False),
    ("put on", "", "穿上；戴上；上演", "13", False),

    # ===== Q =====
    ("queue", "/kjuː/", "n. 队列；长队", "13", False),
    ("quickly", "/'kwɪkli/", "adv. 迅速地；快速地", "61", False),
    ("quietly", "/'kwaɪətli/", "adv. 安静地；轻声地", "13", False),
    ("quite", "/kwaɪt/", "adv. 相当；很", "7", False),
    ("quite a", "", "相当；很", "7", False),

    # ===== R =====
    ("race", "/reɪs/", "n. 比赛；赛跑", "35", False),
    ("racket", "/'rækɪt/", "n. (网球等的)球拍", "18", False),
    ("rain or shine", "", "不论晴雨；风雨无阻", "41", False),
    ("real", "/rɪəl/", "adj. 真实的；真正的", "62", False),
    ("realize", "/'rɪəlaɪz/", "v. (=realise) 意识到；实现", "51", False),
    ("record", "/'rekɔːd/", "n. 记录；唱片", "54", False),
    ("record", "/rɪ'kɔːd/", "v. 记录；录音", "54", False),
    ("relax", "/rɪ'læks/", "v. 放松；休息", "14", False),
    ("remove", "/rɪ'muːv/", "v. 移开；去除", "51", False),
    ("respect", "/rɪ'spekt/", "n. & v. 尊重；尊敬", "10", False),
    ("rest", "/rest/", "n. 休息；剩余部分", "46", False),
    ("rest area", "", "休息区", "46", False),
    ("result", "/rɪ'zʌlt/", "n. 结果；成绩", "31", False),
    ("rich", "/rɪtʃ/", "adj. 富有的；丰富的", "63", False),
    ("ride", "/raɪd/", "v. (rode; ridden) 骑 n. 骑行", "34", False),
    ("right now", "", "立刻；马上", "34", False),
    ("road", "/rəʊd/", "n. 路；道路", "53", False),
    ("rock", "/rɒk/", "n. 岩石；石头", "46", False),
    ("rope", "/rəʊp/", "n. 绳子；绳索", "18", False),
    ("rule", "/ruːl/", "n. 规则；规章", "9", False),
    ("run after", "", "追赶", "47", False),
    ("rush", "/rʌʃ/", "v. & n. 冲；匆忙", "38", False),
    ("rush hour", "", "(上下班)高峰时间", "38", False),

    # ===== S =====
    ("salad", "/'sæləd/", "n. 沙拉", "26", False),
    ("salt", "/sɔːlt; sɒlt/", "n. 盐", "30", False),
    ("sandwich", "/'sænwɪtʃ; 'sænwɪdʒ/", "n. 三明治", "3", False),
    ("save", "/seɪv/", "v. 救；节省；保存", "6", False),
    ("scary", "/'skeəri/", "adj. 可怕的；吓人的", "5", False),
    ("screen", "/skriːn/", "n. 屏幕；银幕", "51", False),
    ("search", "/sɜːtʃ/", "v. 搜索；查找", "62", False),
    ("search for", "", "搜索；寻找", "62", False),
    ("seem", "/siːm/", "v. 似乎；好像", "46", False),
    ("seldom", "/'seldəm/", "adv. 很少；不常", "19", False),
    ("serve", "/sɜːv/", "v. 服务；提供(食物等)", "29", False),
    ("set", "/set/", "v. (set) 放置；设定", "63", False),
    ("set ... free", "", "释放；使自由", "63", False),
    ("shark", "/ʃɑːk/", "n. 鲨鱼", "5", False),
    ("shh", "/ʃ/", "interj. (=sh) 嘘（示意安静）", "13", False),
    ("shine", "/ʃaɪn/", "v. (shone) 发光；照耀 n. 光亮", "38", False),
    ("shout", "/ʃaʊt/", "v. & n. 呼喊；喊叫", "47", False),
    ("shuttlecock", "/'ʃʌtlkɒk/", "n. 羽毛球（指球）", "37", False),
    ("side", "/saɪd/", "n. 边；侧；面", "38", False),
    ("side by side", "", "肩并肩地；并排地", "38", False),
    ("sight", "/saɪt/", "n. 视力；看见；景象", "37", False),
    ("silly", "/'sɪli/", "adj. 愚蠢的；傻的", "59", False),
    ("sir", "/sɜː(r)/", "n. 先生", "29", False),
    ("sit-up", "/'sɪtʌp/", "n. 仰卧起坐", "22", False),
    ("size", "/saɪz/", "n. 大小；尺寸", "63", False),
    ("skate", "/skeɪt/", "v. 滑冰", "37", False),
    ("skateboard", "/'skeɪtbɔːd/", "n. 滑板", "22", False),
    ("skateboarding", "/'skeɪtbɔːdɪŋ/", "n. 滑板运动", "22", False),
    ("skill", "/skɪl/", "n. 技能；技巧", "54", False),
    ("sleepy", "/'sliːpi/", "adj. 困倦的；想睡的", "30", False),
    ("slowly", "/'sləʊli/", "adv. 缓慢地", "38", False),
    ("smile", "/smaɪl/", "v. & n. 微笑", "61", False),
    ("snack", "/snæk/", "n. 零食；小吃", "11", False),
    ("snake", "/sneɪk/", "n. 蛇", "5", False),
    ("snowman", "/'snəʊmæn/", "n. (pl. snowmen) 雪人", "44", False),
    ("snowy", "/'snəʊi/", "adj. 下雪的；多雪的", "45", False),
    ("soft", "/sɒft/", "adj. 柔软的；柔和的", "31", False),
    ("soft drink", "", "软饮料（不含酒精）", "31", False),
    ("some day", "", "有一天；改天", "43", False),
    ("somebody", "/'sʌmbədi/", "pron. 某人", "36", False),
    ("someone", "/'sʌmwʌn/", "pron. 某人；有人", "63", False),
    ("sometime", "/'sʌmtaɪm/", "adv. 在某个时候", "19", False),
    ("south", "/saʊθ/", "n. 南方；南部 adj. 南方的", "42", False),
    ("spirit", "/'spɪrɪt/", "n. 精神；情绪", "14", False),
    ("stay in", "", "待在家里；不外出", "42", False),
    ("step", "/step/", "n. 步骤；脚步", "51", False),
    ("still", "/stɪl/", "adv. 仍然；还", "46", False),
    ("storm", "/stɔːm/", "n. 暴风雨", "47", False),
    ("stormy", "/'stɔːmi/", "adj. 有暴风雨的", "42", False),
    ("straight", "/streɪt/", "adv. 笔直地；直接地 adj. 直的", "54", False),
    ("strawberry", "/'strɔːbəri/", "n. 草莓", "28", False),
    ("subway", "/'sʌbweɪ/", "n. 地铁", "38", False),
    ("succeed", "/sək'siːd/", "v. 成功；达到", "22", False),
    ("succeed in doing sth", "", "成功做某事", "63", False),
    ("such", "/sʌtʃ/", "adj. 这样的；如此的 pron. 这样的人/事物", "38", False),
    ("such as", "", "例如；像……这样", "38", False),
    ("suddenly", "/'sʌdənli/", "adv. 突然地", "59", False),
    ("sugar", "/'ʃʊɡə(r)/", "n. 糖", "29", False),
    ("sunbathe", "/'sʌnbeɪð/", "v. 沐日光浴", "43", False),
    ("sunlight", "/'sʌnlaɪt/", "n. 阳光；日光", "46", False),
    ("sunshine", "/'sʌnʃaɪn/", "n. 阳光", "39", False),
    ("swan", "/swɒn/", "n. 天鹅", "62", False),
    ("sweet", "/swiːt/", "n. 糖果 adj. 甜的", "11", False),
    ("swimmer", "/'swɪmə(r)/", "n. 游泳者", "6", False),

    # ===== T =====
    ("take message", "", "捎口信", "36", False),
    ("take care of", "", "照顾；照料", "2", False),
    ("take part in", "", "参加；参与", "39", False),
    ("taste", "/teɪst/", "v. 品尝；尝起来 n. 味道", "27", False),
    ("teach", "/tiːtʃ/", "v. (taught) 教；教授", "54", False),
    ("team", "/tiːm/", "n. 队；组", "22", False),
    ("teenager", "/'tiːneɪdʒə(r)/", "n. 青少年", "23", False),
    ("tell the truth", "", "说实话", "60", False),
    ("temperature", "/'temprətʃə(r)/", "n. 温度", "44", False),
    ("tent", "/tent/", "n. 帐篷", "54", False),
    ("terrible", "/'terəbl/", "adj. 可怕的；糟糕的", "53", False),
    ("Thai", "/taɪ/", "adj. 泰国的 n. 泰国人；泰语", "6", False),
    ("theatre", "/'θɪətə(r)/", "n. 剧院；戏院", "52", False),
    ("theirs", "/ðeəz/", "pron. 他们的（名词性物主代词）", "20", False),
    ("think about", "", "思考；考虑", "14", False),
    ("think of", "", "想起；想到", "54", False),
    ("thirsty", "/'θɜːsti/", "adj. 口渴的", "31", False),
    ("thought", "/θɔːt/", "n. 想法；思想", "54", False),
    ("through", "/θruː/", "prep. 穿过；通过", "46", False),
    ("time zone", "", "时区", "38", False),
    ("tiring", "/'taɪərɪŋ/", "adj. 令人疲倦的；累人的", "46", False),
    ("to sb's surprise", "", "令某人惊讶的是", "62", False),
    ("too ... to", "", "太……而不能", "30", False),
    ("too many", "", "太多（可数名词）", "6", False),
    ("too much", "", "太多（不可数名词）", "29", False),
    ("tour", "/tʊə(r)/", "n. & v. 旅行；观光", "39", False),
    ("tourist", "/'tʊərɪst/", "n. 游客；旅行者", "45", False),
    ("treat", "/triːt/", "v. 对待；治疗；款待 n. 款待", "14", False),
    ("trick", "/trɪk/", "n. 诡计；把戏", "22", False),
    ("trip", "/trɪp/", "n. 旅行", "51", False),
    ("true", "/truː/", "adj. 真实的；正确的", "60", False),
    ("trunk", "/trʌŋk/", "n. 象鼻；树干", "6", False),
    ("truth", "/truːθ/", "n. 真相；事实", "60", False),
    ("try on", "", "试穿", "53", False),
    ("T-shirt", "/'tiː ʃɜːt/", "n. T恤衫", "21", False),
    ("turn off", "", "关掉（水、电等）", "11", False),
    ("twice", "/twaɪs/", "adv. 两次；两倍", "18", False),

    # ===== U =====
    ("ugly", "/'ʌɡli/", "adj. 丑陋的；难看的", "62", False),
    ("understand", "/ˌʌndə'stænd/", "v. (understood) 理解；明白", "15", False),
    ("unhappy", "/ʌn'hæpi/", "adj. 不快乐的；不高兴的", "14", False),
    ("uniform", "/'juːnɪfɔːm/", "n. 制服；校服", "10", False),
    ("untidy", "/ʌn'taɪdi/", "adj. 不整洁的；凌乱的", "15", False),
    ("upon", "/ə'pɒn/", "prep. 在……上", "57", False),
    ("used to", "", "过去常常（做某事）", "51", False),

    # ===== V =====
    ("voice", "/vɔɪs/", "n. 嗓音；声音", "35", False),
    ("volleyball", "/'vɒlibɔːl/", "n. 排球运动", "20", False),

    # ===== W =====
    ("waiter", "/'weɪtə(r)/", "n. （男）服务员", "27", False),
    ("waitress", "/'weɪtrəs/", "n. 女服务员", "29", False),
    ("war", "/wɔː(r)/", "n. 战争", "58", False),
    ("waste", "/weɪst/", "n. 浪费；废物 v. 浪费", "51", False),
    ("wastewater", "/'weɪstwɔːtə(r)/", "n. 废水", "51", False),
    ("watermelon", "/'wɔːtəˌmelən/", "n. 西瓜", "26", False),
    ("weekday", "/'wiːkdeɪ/", "n. 工作日（周一至周五任一天）", "10", False),
    ("weight", "/weɪt/", "n. 重量；体重", "30", False),
    ("well-used", "/ˌwel 'juːzd/", "adj. 常用的；使用得多的", "19", False),
    ("west", "/west/", "n. 西方；西部 adj. 西方的", "42", False),
    ("wet", "/wet/", "adj. 湿的；潮湿的", "46", False),
    ("whale", "/weɪl/", "n. 鲸", "5", False),
    ("What about ...?", "", "……怎么样？", "27", False),
    ("wind", "/wɪnd/", "n. 风", "47", False),
    ("wise", "/waɪz/", "adj. 明智的；聪明的", "58", False),
    ("wolf", "/wʊlf/", "n. (pl. wolves) 狼", "2", False),
    ("work on", "", "从事；致力于", "34", False),
    ("work out", "", "锻炼；计算出", "22", False),
    ("working", "/'wɜːkɪŋ/", "adj. 工作的", "21", False),
    ("working day", "", "工作日", "21", False),
    ("wow", "/waʊ/", "interj. 哇；呀", "37", False),
    ("write down", "", "写下；记下", "54", False),

    # ===== Z =====
    ("zone", "/zəʊn/", "n. 区域；地带", "38", False),
]

def generate_md(vocab, title, output_path):
    lines = [f"# {title}\n"]
    lines.append("> 注：加 `*` 的词为《义务教育英语课程标准（2022年版）》中的二级词。\n")
    lines.append("---\n")
    import string
    for letter in string.ascii_uppercase:
        group = [(w, p, c, pg, k) for w, p, c, pg, k in vocab
                 if w.lstrip('*').upper().startswith(letter)]
        if group:
            lines.append(f"## {letter}\n")
            lines.append("| 单词 | 音标 | 释义 | 页码 |")
            lines.append("|------|------|------|------|")
            for w, p, c, pg, k in group:
                phonetic = p if p else ""
                lines.append(f"| {w} | {phonetic} | {c} | p. {pg} |")
            lines.append("")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return len(vocab)

out = os.path.join(BASE, '七年级下册词汇表.md')
n = generate_md(C1B_VOCAB, "人教版 PEP 七年级下册词汇表", out)
key_count = sum(1 for _,_,_,_,k in C1B_VOCAB if k)
print(f"Generated: {out}")
print(f"Total: {n} entries (key: {key_count}, non-key: {n - key_count})")