#!/usr/bin/env python3
"""Generate 初一上册词汇表.md from OCR-extracted vocabulary."""
import os

BASE = '/Users/allen/Downloads/人教版(PEP)'

# 初一上册 (Grade 7, Semester 1) Vocabulary
# Format: (word, phonetic, chinese_meaning, page, is_key)
C1_VOCAB = [
    # ===== A =====
    ("ability", "/ə'bɪləti/", "n. 能力", "4", False),
    ("across", "/ə'krɒs/", "adv. & prep. 穿过；横过", "36", False),
    ("across from", "", "在……对面", "36", False),
    ("act", "/ækt/", "v. 行动；表演 n. 行为", "56", False),
    ("act out", "", "表演出来", "56", False),
    ("activity", "/æk'tɪvəti/", "n. 活动", "30", False),
    ("a lot", "", "许多；大量", "23", False),
    ("a lot of / lots of", "", "许多；大量", "29", False),
    ("AM / a.m.", "/ˌeɪ 'em/", "上午", "48", False),
    ("amazing", "/ə'meɪzɪŋ/", "adj. 令人惊奇的", "64", False),
    ("another", "/ə'nʌðə(r)/", "adj. & pron. 另一个", "60", False),
    ("around", "/ə'raʊnd/", "adv. & prep. 在周围；大约", "36", False),
    ("as", "/æz; əz/", "prep. 作为 conj. 当……时；因为", "47", False),
    ("at home", "", "在家", "56", False),
    ("at night", "", "在晚上", "32", False),
    ("at school", "", "在学校", "40", False),
    ("at the back (of)", "", "在（……）后面", "38", False),
    ("at weekends", "", "在周末", "63", False),
    # ===== B =====
    ("balloon", "/bə'luːn/", "n. 气球", "70", False),
    ("band", "/bænd/", "n. 乐队；带子", "23", False),
    ("bat", "/bæt/", "n. 球棒；蝙蝠", "29", False),
    ("beef", "/biːf/", "n. 牛肉", "56", False),
    ("bell", "/bel/", "n. 铃(声)；钟(声)", "4", False),
    ("biology", "/baɪ'ɒlədʒi/", "n. 生物学", "44", False),
    ("blow", "/bləʊ/", "v. 吹；刮", "72", False),
    ("blow out", "", "吹灭", "72", False),
    ("bookcase", "/'bʊkkeɪs/", "n. 书柜", "39", False),
    ("boring", "/'bɔːrɪŋ/", "adj. 无聊的", "44", False),
    ("both", "/bəʊθ/", "adj. & pron. 两者都", "30", False),
    ("bottle", "/'bɒtl/", "n. 瓶子", "7", False),
    ("break", "/breɪk/", "n. 休息 v. 打破", "40", False),
    ("brush", "/brʌʃ/", "v. 刷 n. 刷子", "60", False),
    ("building", "/'bɪldɪŋ/", "n. 建筑物", "36", False),
    ("bye for now", "", "再见", "41", False),
    # ===== C =====
    ("carrot", "/'kærət/", "n. 胡萝卜", "13", False),
    ("celebrate", "/'selɪbreɪt/", "v. 庆祝", "67", False),
    ("celebration", "/ˌselɪ'breɪʃn/", "n. 庆祝；庆典", "72", False),
    ("centre / center", "/'sentə(r)/", "n. 中心", "36", False),
    ("change", "/tʃeɪndʒ/", "v. & n. 改变；变化", "40", False),
    ("chess", "/tʃes/", "n. 国际象棋", "30", False),
    ("Chinese chess", "", "中国象棋", "30", False),
    ("chocolate", "/'tʃɒklət/", "n. 巧克力", "70", False),
    ("choose", "/tʃuːz/", "v. 选择", "52", False),
    ("circle", "/'sɜːkl/", "v. 圈出 n. 圆；圈", "17", False),
    ("class teacher", "", "班主任", "21", False),
    ("classmate", "/'klɑːsmeɪt/", "n. 同学", "21", False),
    ("climb", "/klaɪm/", "v. 爬；攀登", "55", False),
    ("club", "/klʌb/", "n. 俱乐部", "51", False),
    ("collect", "/kə'lekt/", "v. 收集；采集", "56", False),
    ("contact", "/'kɒntækt/", "n. 联系 v. 接触", "72", False),
    ("conversation", "/ˌkɒnvə'seɪʃn/", "n. 对话；交谈", "4", False),
    ("corner", "/'kɔːnə(r)/", "n. 角落", "38", False),
    ("count", "/kaʊnt/", "v. 数数", "16", False),
    ("country", "/'kʌntri/", "n. 国家", "22", False),
    # ===== D =====
    ("daily", "/'deɪli/", "adj. 日常的", "64", False),
    ("daily routine", "", "日常作息", "64", False),
    ("dark", "/dɑːk/", "adj. 黑暗的", "64", False),
    ("delicious", "/dɪ'lɪʃəs/", "adj. 美味的", "40", False),
    ("different", "/'dɪfrənt/", "adj. 不同的", "56", False),
    ("different from", "", "与……不同", "40", False),
    ("dining hall", "/'daɪnɪŋ hɔːl/", "餐厅", "36", False),
    ("discover", "/dɪ'skʌvə(r)/", "v. 发现", "56", False),
    ("do exercises", "", "做运动；做练习", "40", False),
    ("drama", "/'drɑːmə/", "n. 戏剧", "52", False),
    ("drawer", "/drɔː(r)/", "n. 抽屉", "37", False),
    ("drum", "/drʌm/", "n. 鼓", "53", False),
    ("duty", "/'djuːti/", "n. 职责；义务", "60", False),
    # ===== E =====
    ("each", "/iːtʃ/", "adj. & pron. 每个", "2", False),
    ("each other", "", "互相", "2", False),
    ("else", "/els/", "adv. 其他的；另外", "17", False),
    ("enjoy", "/ɪn'dʒɔɪ/", "v. 享受；喜欢", "72", False),
    ("eraser", "/ɪ'reɪzə(r)/", "n. 橡皮", "7", False),
    ("even", "/'iːvn/", "adv. 甚至", "24", False),
    ("every day", "", "每天", "29", False),
    ("everyday", "/'evrideɪ/", "adj. 日常的", "64", False),
    ("everyone", "/'evriwʌn/", "pron. 每人", "2", False),
    ("exactly", "/ɪɡ'zæktli/", "adv. 精确地；正好", "53", False),
    ("example", "/ɪɡ'zɑːmpl/", "n. 例子；榜样", "71", False),
    ("excellent", "/'eksələnt/", "adj. 优秀的", "48", False),
    ("exciting", "/ɪk'saɪtɪŋ/", "adj. 令人兴奋的", "44", False),
    # ===== F =====
    ("fall", "/fɔːl/", "v. & n. 落下；秋天", "40", False),
    ("fall in love with", "", "爱上……", "56", False),
    ("feeling", "/'fiːlɪŋ/", "n. 感觉；情感", "52", False),
    ("field", "/fiːld/", "n. 田地；场地", "36", False),
    ("finish", "/'fɪnɪʃ/", "v. 完成；结束", "64", False),
    ("Finnish", "/'fɪnɪʃ/", "n. 芬兰语 adj. 芬兰的", "64", False),
    ("first name", "", "名（名字）", "21", False),
    ("fishing rod", "/rɒd/", "钓鱼竿", "29", False),
    ("flag", "/flæɡ/", "n. 旗", "40", False),
    ("for example", "", "例如", "71", False),
    ("found", "/faʊnd/", "v. 创建；发现（find的过去式）", "71", False),
    ("French", "/frentʃ/", "n. 法语 adj. 法国的", "48", False),
    ("full", "/fʊl/", "adj. 满的；饱的", "20", False),
    ("full name", "", "全名", "20", False),
    ("fun", "/fʌn/", "n. 乐趣 adj. 有趣的", "13", False),
    ("funny", "/'fʌni/", "adj. 有趣的；好笑的", "31", False),
    ("future", "/'fjuːtʃə(r)/", "n. 未来", "48", False),
    # ===== G =====
    ("geography", "/dʒi'ɒɡrəfi/", "n. 地理(学)", "44", False),
    ("get dressed", "", "穿衣服", "60", False),
    ("get to know", "", "了解；认识", "20", False),
    ("get up", "", "起床", "60", False),
    ("go hiking", "/'haɪkɪŋ/", "去远足", "33", False),
    ("go to bed", "", "上床睡觉", "61", False),
    ("good at", "", "擅长", "47", False),
    ("good with", "", "善于应付……", "45", False),
    ("goose (pl. geese)", "/ɡuːs/", "n. 鹅", "14", False),
    ("grade", "/ɡreɪd/", "n. 年级；等级", "20", False),
    ("grandchild", "/'ɡræntʃaɪld/", "n. (外)孙子；(外)孙女", "32", False),
    ("grandparent", "/'ɡrænpeərənt/", "n. 祖父母", "31", False),
    ("greet", "/ɡriːt/", "v. 问候；迎接", "1", False),
    ("grow", "/ɡrəʊ/", "v. 生长；增长；种植", "72", False),
    ("guitar", "/ɡɪ'tɑː(r)/", "n. 吉他", "24", False),
    ("gym", "/dʒɪm/", "n. 体育馆；健身房", "36", False),
    # ===== H =====
    ("hall", "/hɔːl/", "n. 大厅；礼堂", "36", False),
    ("handsome", "/'hænsəm/", "adj. 英俊的", "44", False),
    ("hat", "/hæt/", "n. 帽子", "32", False),
    ("have fun", "", "玩得开心", "31", False),
    ("height", "/haɪt/", "n. 高度；身高", "72", False),
    ("help sb with", "", "帮助某人做……", "45", False),
    ("hey", "/heɪ/", "interj. 嘿；喂", "24", False),
    ("hike", "/haɪk/", "v. & n. 远足；徒步", "33", False),
    ("history", "/'hɪstri/", "n. 历史", "44", False),
    ("hobby", "/'hɒbi/", "n. 爱好", "25", False),
    ("hockey", "/'hɒki/", "n. 曲棍球", "64", False),
    ("homework", "/'həʊmwɜːk/", "n. 家庭作业", "61", False),
    ("housework", "/'haʊswɜːk/", "n. 家务", "63", False),
    ("How about ...?", "", "……怎么样？", "40", False),
    ("husband", "/'hʌzbənd/", "n. 丈夫", "28", False),
    # ===== I =====
    ("ice hockey", "", "冰球", "64", False),
    ("important", "/ɪm'pɔːtnt/", "adj. 重要的", "37", False),
    ("in class", "", "在课堂上", "48", False),
    ("in front of", "", "在……前面", "36", False),
    ("in the future", "", "在未来", "48", False),
    ("in the middle", "", "在中间", "32", False),
    ("information", "/ˌɪnfə'meɪʃn/", "n. 信息", "25", False),
    ("insect", "/'ɪnsekt/", "n. 昆虫", "56", False),
    ("instrument", "/'ɪnstrəmənt/", "n. 乐器；工具", "48", False),
    ("interested", "/'ɪntrəstɪd/", "adj. 感兴趣的", "56", False),
    ("interested in", "", "对……感兴趣", "56", False),
    ("international", "/ˌɪntə'næʃnəl/", "adj. 国际的", "71", False),
    ("IT", "/ˌaɪ 'tiː/", "信息技术", "44", False),
    # ===== J =====
    ("join", "/dʒɔɪn/", "v. 加入；参加", "51", False),
    # ===== K =====
    ("key", "/kiː/", "n. 钥匙；关键", "7", False),
    ("kilo", "/'kiːləʊ/", "n. 千克；公斤", "69", False),
    ("knee", "/niː/", "n. 膝盖", "32", False),
    # ===== L =====
    ("language", "/'læŋɡwɪdʒ/", "n. 语言", "71", False),
    ("large", "/lɑːdʒ/", "adj. 大的", "37", False),
    ("last name", "", "姓", "20", False),
    ("later", "/'leɪtə(r)/", "adv. & adj. 后来(的)", "72", False),
    ("laugh", "/lɑːf/", "v. 笑 n. 笑声", "31", False),
    ("life", "/laɪf/", "n. 生活；生命", "48", False),
    ("list", "/lɪst/", "n. 清单；列表 v. 列举", "70", False),
    ("listen to", "", "听……", "47", False),
    ("locker", "/'lɒkə(r)/", "n. 储物柜", "37", False),
    ("look at", "", "看", "17", False),
    # ===== M =====
    ("magic", "/'mædʒɪk/", "n. 魔法 adj. 有魔力的", "48", False),
    ("make a wish", "", "许愿", "72", False),
    ("make friends", "", "交朋友", "19", False),
    ("make use of", "", "利用", "59", False),
    ("mark", "/mɑːk/", "v. 标记 n. 分数", "64", False),
    ("mean", "/miːn/", "v. 意思是", "27", False),
    ("meaningful", "/'miːnɪŋfl/", "adj. 有意义的", "72", False),
    ("member", "/'membə(r)/", "n. 成员", "30", False),
    ("mind", "/maɪnd/", "n. 头脑；心思", "56", False),
    ("mistake", "/mɪ'steɪk/", "n. 错误", "21", False),
    ("modern", "/'mɒdn/", "adj. 现代的", "40", False),
    ("more", "/mɔː(r)/", "adj. & pron. 更多的", "55", False),
    ("more than", "", "多于；超过", "55", False),
    ("most", "/məʊst/", "adj. & pron. 最多的 adv. 最", "40", False),
    ("musical", "/'mjuːzɪkl/", "adj. 音乐的", "53", False),
    ("musical instrument", "", "乐器", "53", False),
    # ===== N =====
    ("national", "/'næʃnəl/", "adj. 国家的；民族的", "71", False),
    ("nature", "/'neɪtʃə(r)/", "n. 自然", "56", False),
    ("need", "/niːd/", "v. & n. 需要", "10", False),
    ("news", "/njuːz/", "n. 新闻；消息", "53", False),
    ("next time", "", "下次", "72", False),
    ("next to", "", "在……旁边", "33", False),
    ("notice", "/'nəʊtɪs/", "n. 通知 v. 注意到", "37", False),
    ("number", "/'nʌmbə(r)/", "n. 数字；号码", "45", False),
    # ===== O =====
    ("office", "/'ɒfɪs/", "n. 办公室", "36", False),
    ("oh", "/əʊ/", "interj. 哦", "2", False),
    ("on duty", "", "值日", "60", False),
    ("only", "/'əʊnli/", "adv. 仅仅；只", "64", False),
    ("other", "/'ʌðə(r)/", "pron. 其他的 adj. 别的", "2", False),
    ("outside", "/ˌaʊt'saɪd/", "adv. & prep. 在外面 adj. 外面的", "29", False),
    ("own", "/əʊn/", "adj. & pron. 自己的", "71", False),
    # ===== P =====
    ("page", "/peɪdʒ/", "n. 页", "24", False),
    ("paint", "/peɪnt/", "v. 画画；涂漆 n. 颜料", "54", False),
    ("parrot", "/'pærət/", "n. 鹦鹉", "24", False),
    ("part", "/pɑːt/", "n. 部分", "64", False),
    ("past", "/pɑːst/", "n. 过去 adj. 过去的 prep. 经过", "62", False),
    ("ping-pong bat", "", "乒乓球拍", "29", False),
    ("pizza", "/'piːtsə/", "n. 比萨饼", "70", False),
    ("play Chinese chess", "", "下中国象棋", "52", False),
    ("play ping-pong", "", "打乒乓球", "29", False),
    ("play the guitar", "", "弹吉他", "24", False),
    ("PM / p.m.", "/ˌpiː 'em/", "下午", "48", False),
    ("post", "/pəʊst/", "n. 帖子 v. 邮寄", "72", False),
    ("pot", "/pɒt/", "n. 锅", "23", False),
    ("prepare", "/prɪ'peə(r)/", "v. 准备", "64", False),
    ("prepare sth for", "", "为……准备某物", "64", False),
    ("price", "/praɪs/", "n. 价格", "70", False),
    ("problem", "/'prɒbləm/", "n. 问题", "48", False),
    ("put up", "", "张贴；搭建", "37", False),
    # ===== Q =====
    ("quarter", "/'kwɔːtə(r)/", "n. 四分之一；一刻钟", "60", False),
    # ===== R =====
    ("raise", "/reɪz/", "v. 举起；筹集", "40", False),
    ("really", "/'riːəli/", "adv. 真正地；确实", "71", False),
    ("reason", "/'riːzn/", "n. 原因；理由", "46", False),
    ("remember", "/rɪ'membə(r)/", "v. 记住；记得", "47", False),
    ("reporter", "/rɪ'pɔːtə(r)/", "n. 记者", "61", False),
    ("restaurant", "/'restrɒnt/", "n. 餐馆", "63", False),
    ("rise", "/raɪz/", "v. 上升；升起 n. 增加", "61", False),
    ("routine", "/ruː'tiːn/", "n. 常规；惯例", "62", False),
    # ===== S =====
    ("sale", "/seɪl/", "n. 销售；特价", "69", False),
    ("same", "/seɪm/", "adj. 相同的", "23", False),
    ("saying", "/'seɪɪŋ/", "n. 谚语；格言", "61", False),
    ("scientist", "/'saɪəntɪst/", "n. 科学家", "48", False),
    ("screen", "/skriːn/", "n. 屏幕", "39", False),
    ("seat", "/siːt/", "n. 座位", "40", False),
    ("section", "/'sekʃn/", "n. 部分；章节", "1", False),
    ("send", "/send/", "v. 发送；寄", "40", False),
    ("shower", "/'ʃaʊə(r)/", "n. 淋浴；阵雨 v. 淋浴", "60", False),
    ("similar", "/'sɪmələ(r)/", "adj. 相似的", "41", False),
    ("similar to", "", "与……相似", "41", False),
    ("singer", "/'sɪŋə(r)/", "n. 歌手", "48", False),
    ("smart", "/smɑːt/", "adj. 聪明的；智能的", "37", False),
    ("something", "/'sʌmθɪŋ/", "pron. 某事；某物", "69", False),
    ("son", "/sʌn/", "n. 儿子", "33", False),
    ("soon", "/suːn/", "adv. 不久；很快", "56", False),
    ("sound", "/saʊnd/", "v. 听起来 n. 声音", "41", False),
    ("special", "/'speʃl/", "adj. 特别的", "37", False),
    ("spell", "/spel/", "v. 拼写", "4", False),
    ("spend", "/spend/", "v. 花费（时间、金钱）", "29", False),
    ("sports field", "", "运动场", "36", False),
    ("start", "/stɑːt/", "v. 开始", "4", False),
    ("starter unit", "", "起始单元", "1", False),
    ("stay", "/steɪ/", "v. 停留；保持", "62", False),
    ("surprise", "/sə'praɪz/", "n. 惊喜 v. 使惊讶", "69", False),
    ("symbol", "/'sɪmbl/", "n. 象征；符号", "72", False),
    # ===== T =====
    ("take a photo", "", "拍照", "72", False),
    ("take a shower", "", "淋浴", "60", False),
    ("take photos", "", "拍照", "56", False),
    ("tennis", "/'tenɪs/", "n. 网球", "24", False),
    ("term", "/tɜːm/", "n. 学期", "48", False),
    ("than", "/ðæn; ðən/", "prep. & conj. 比", "56", False),
    ("thing", "/θɪŋ/", "n. 东西；事情", "10", False),
    ("tofu", "/'təʊfuː/", "n. 豆腐", "23", False),
    ("together", "/tə'ɡeðə(r)/", "adv. 一起", "29", False),
    ("tooth (pl. teeth)", "/tuːθ/", "n. 牙齿", "60", False),
    ("total", "/'təʊtl/", "n. 总数 adj. 总的", "69", False),
    ("twin", "/twɪn/", "n. 双胞胎之一 adj. 双胞胎的", "23", False),
    # ===== U =====
    ("unit", "/'juːnɪt/", "n. 单元", "1", False),
    ("useful", "/'juːsfl/", "adj. 有用的", "44", False),
    ("usually", "/'juːʒuəli/", "adv. 通常", "60", False),
    # ===== V =====
    ("village", "/'vɪlɪdʒ/", "n. 村庄", "72", False),
    ("violin", "/ˌvaɪə'lɪn/", "n. 小提琴", "31", False),
    # ===== W =====
    ("weekend", "/ˌwiːk'end/", "n. 周末", "63", False),
    ("while", "/waɪl/", "n. 一段时间 conj. 当……时", "63", False),
    ("whiteboard", "/'waɪtbɔːd/", "n. 白板", "37", False),
    ("whom", "/huːm/", "pron. 谁（宾格）", "73", False),
    ("wildlife", "/'waɪldlaɪf/", "n. 野生动物", "56", False),
    ("work out", "", "计算出；锻炼", "48", False),
    ("would", "/wʊd; wəd/", "modal v. 愿意", "24", False),
    ("would ('d) like to", "", "想要", "24", False),
    # ===== Y =====
    ("yard", "/jɑːd/", "n. 院子；码", "13", False),
    ("yogurt", "/'jɒɡət/", "n. 酸奶", "69", False),
    ("You're welcome.", "", "不用谢。", "11", False),
    ("yours", "/jɔːz/", "pron. 你的（名词性）", "40", False),
]

def generate_md(vocab, title, output_path):
    lines = [f"# {title}\n"]
    lines.append("> 注：加 `*` 的词为《义务教育英语课程标准（2022年版）》中的二级词。\n")
    lines.append("---\n")
    import string
    for letter in string.ascii_uppercase:
        group = [(w, p, c, pg, k) for w, p, c, pg, k in vocab
                 if w.lstrip('*').upper().startswith(letter)]
        if group:
            lines.append(f"## {letter}\n")
            lines.append("| 单词 | 音标 | 释义 | 页码 |")
            lines.append("|------|------|------|------|")
            for w, p, c, pg, k in group:
                phonetic = p if p else ""
                lines.append(f"| {w} | {phonetic} | {c} | p. {pg} |")
            lines.append("")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return len(vocab)

out = os.path.join(BASE, '七年级上册词汇表.md')
n = generate_md(C1_VOCAB, "人教版 PEP 七年级上册词汇表", out)
key_count = sum(1 for _,_,_,_,k in C1_VOCAB if k)
print(f"Generated: {out}")
print(f"Total: {n} entries (key: {key_count}, non-key: {n - key_count})")