#!/usr/bin/env python3
"""Generate 八年级上册词汇表.md from OCR-extracted vocabulary."""
import os

BASE = '/Users/allen/Downloads/人教版(PEP)'

C2A_VOCAB = [
    # ===== A =====
    ("able", "/'eɪbl/", "adj. 能够的；有能力的", "56", False),
    ("accept", "/ək'sept/", "v. 接受；同意", "66", False),
    ("accident", "/'æksɪdənt/", "n. 事故；意外", "28", False),
    ("according to", "", "根据；按照", "47", False),
    ("accordion", "/ə'kɔːdiən/", "n. 手风琴", "7", False),
    ("achieve", "/ə'tʃiːv/", "v. 实现；达到", "56", False),
    ("action", "/'ækʃn/", "n. 行动；行为", "36", False),
    ("actress", "/'æktrəs/", "n. 女演员", "54", False),
    ("actually", "/'æktʃuəli/", "adv. 实际上；事实上", "33", False),
    ("add", "/æd/", "v. 增加；添加", "14", False),
    ("add sth to sth", "", "把……加到……上", "14", False),
    ("African", "/'æfrɪkən/", "adj. 非洲的 n. 非洲人", "35", False),
    ("against", "/ə'ɡenst/", "prep. 反对；靠着；对……不利", "6", False),
    ("ah", "/ɑː/", "interj. 啊（表示惊讶等）", "16", False),
    ("ahead", "/ə'hed/", "adv. 在前面；向前", "57", False),
    ("AI", "/ˌeɪ 'aɪ/", "n. (= artificial intelligence) 人工智能", "52", False),
    ("alike", "/ə'laɪk/", "adj. 相像的 adv. 相似地", "26", False),
    ("almost", "/'ɔːlməʊst/", "adv. 几乎；差不多", "16", False),
    ("alone", "/ə'ləʊn/", "adv. & adj. 独自；单独", "22", False),
    ("along with sb/sth", "", "与……一起；连同", "46", False),
    ("ancient", "/'eɪnʃənt/", "adj. 古代的；古老的", "2", False),
    ("ant", "/ænt/", "n. 蚂蚁", "37", False),
    ("anywhere", "/'eniweə(r)/", "adv. & pron. 任何地方", "3", False),
    ("apartment", "/ə'pɑːtmənt/", "n. 公寓套房", "18", False),
    ("appear", "/ə'pɪə(r)/", "v. 出现；显得", "34", False),
    ("appearance", "/ə'pɪərəns/", "n. 外貌；外观", "24", False),
    ("argue", "/'ɑːɡjuː/", "v. 争论；争吵", "73", False),
    ("argue with sb", "", "与某人争论", "73", False),
    ("arrival", "/ə'raɪvl/", "n. 到达；抵达", "13", False),
    ("artwork", "/'ɑːtwɜːk/", "n. 艺术作品", "6", False),
    ("as ... as ...", "", "和……一样……", "23", False),
    ("as long as", "", "只要", "69", False),
    ("athlete", "/'æθliːt/", "n. 运动员", "54", False),
    ("at least", "", "至少", "46", False),
    ("attend", "/ə'tend/", "v. 参加；出席", "23", False),
    ("attention", "/ə'tenʃn/", "n. 注意力；专心", "76", False),
    ("average", "/'ævərɪdʒ/", "adj. 平均的 n. 平均数", "6", False),

    # ===== B =====
    ("bake", "/beɪk/", "v. 烘烤；焙", "42", False),
    ("balcony", "/'bælkəni/", "n. 阳台", "12", False),
    ("bamboo", "/ˌbæm'buː/", "n. 竹；竹子", "33", False),
    ("bath", "/bɑːθ/", "n. 洗澡；浴缸", "55", False),
    ("bathroom", "/'bɑːθruːm/", "n. 浴室；卫生间", "12", False),
    ("be careful with", "", "小心；注意", "15", False),
    ("be connected with/to", "", "与……有联系", "36", False),
    ("be home to sb/sth", "", "是……的家园", "37", False),
    ("be tired of", "", "对……感到厌倦", "55", False),
    ("be yourself", "", "做你自己；保持自我", "76", False),
    ("bedroom", "/'bedruːm/", "n. 卧室", "12", False),
    ("believe", "/bɪ'liːv/", "v. 相信；认为", "35", False),
    ("benefit", "/'benɪfɪt/", "v. 使受益 n. 好处", "79", False),
    ("benefit ... from ...", "", "从……中获益", "79", False),
    ("besides", "/bɪ'saɪdz/", "prep. 除……之外 adv. 此外", "23", False),
    ("biscuit", "/'bɪskɪt/", "n. 饼干", "14", False),
    ("block", "/blɒk/", "n. 街区；块 v. 阻挡", "18", False),
    ("boil", "/bɔɪl/", "v. 煮沸；烧开", "42", False),
    ("bored", "/bɔːd/", "adj. 厌倦的；烦闷的", "5", False),
    ("born", "/bɔːn/", "v. 出生 adj. 天生的", "49", False),
    ("borrow", "/'bɒrəʊ/", "v. 借；借用", "14", False),
    ("bowl", "/bəʊl/", "n. 碗；盆", "43", False),
    ("breath", "/breθ/", "n. 呼吸；气息", "3", False),
    ("bridge", "/brɪdʒ/", "n. 桥", "58", False),
    ("budget", "/'bʌdʒɪt/", "n. 预算 v. 编预算", "8", False),
    ("businessman", "/'bɪznəsmæn/", "n. 商人；企业家", "54", False),
    ("butter", "/'bʌtə(r)/", "n. 黄油", "42", False),
    ("butterfly", "/'bʌtəflaɪ/", "n. 蝴蝶", "35", False),
    ("by accident", "", "偶然；意外地", "28", False),

    # ===== C =====
    ("calm", "/kɑːm/", "adj. 镇静的；平静的", "73", False),
    ("camp", "/kæmp/", "n. 营地 v. 露营", "2", False),
    ("cancer", "/'kænsə(r)/", "n. 癌症", "65", False),
    ("care about", "", "关心；在乎", "29", False),
    ("carefully", "/'keəfəli/", "adv. 仔细地；小心地", "76", False),
    ("cash", "/kæʃ/", "n. 现金 v. 兑现", "79", False),
    ("challenge", "/'tʃælɪndʒ/", "n. 挑战 v. 向……挑战", "68", False),
    ("challenging", "/'tʃælɪndʒɪŋ/", "adj. 有挑战性的", "66", False),
    ("chance", "/tʃɑːns/", "n. 机会；可能性", "74", False),
    ("character", "/'kærəktə(r)/", "n. 人物；性格；汉字", "28", False),
    ("cheese", "/tʃiːz/", "n. 奶酪", "42", False),
    ("cheetah", "/'tʃiːtə/", "n. 猎豹", "32", False),
    ("chief", "/tʃiːf/", "adj. 主要的 n. 首领", "66", False),
    ("Christmas", "/'krɪsməs/", "n. 圣诞节", "45", False),
    ("cinnamon", "/'sɪnəmən/", "n. 肉桂", "46", False),
    ("classic", "/'klæsɪk/", "n. 经典作品 adj. 经典的", "53", False),
    ("clause", "/klɔːz/", "n. 从句；条款", "79", False),
    ("clean up", "", "清理；打扫干净", "15", False),
    ("climate", "/'klaɪmət/", "n. 气候", "38", False),
    ("closing", "/'kləʊzɪŋ/", "adj. 结尾的 n. 结束", "79", False),
    ("college", "/'kɒlɪdʒ/", "n. 大学；学院", "46", False),
    ("come over", "", "过来；顺便来访", "69", False),
    ("comfortable", "/'kʌmftəbl/", "adj. 舒适的；舒服的", "5", False),
    ("communicate", "/kə'mjuːnɪkeɪt/", "v. 交流；沟通", "36", False),
    ("communication", "/kəˌmjuːnɪ'keɪʃn/", "n. 交流；沟通", "71", False),
    ("community", "/kə'mjuːnəti/", "n. 社区；团体", "15", False),
    ("compare", "/kəm'peə(r)/", "v. 比较；对比", "21", False),
    ("concert", "/'kɒnsət/", "n. 音乐会", "65", False),
    ("confidence", "/'kɒnfɪdəns/", "n. 信心；自信", "58", False),
    ("confident", "/'kɒnfɪdənt/", "adj. 自信的；有信心的", "56", False),
    ("congratulation", "/kənˌɡrætʃu'leɪʃn/", "n. 祝贺", "23", False),
    ("Congratulations (on ...)!", "", "恭喜（……）！", "23", False),
    ("connect", "/kə'nekt/", "v. 连接；联系", "36", False),
    ("connected", "/kə'nektɪd/", "adj. 有联系的；连接的", "36", False),
    ("connection", "/kə'nekʃn/", "n. 联系；连接", "36", False),
    ("continue", "/kən'tɪnjuː/", "v. 继续；持续", "76", False),
    ("cost", "/kɒst/", "n. 费用；成本 v. 花费", "79", False),
    ("countryside", "/'kʌntrisaɪd/", "n. 乡村；农村", "9", False),
    ("couple", "/'kʌpl/", "n. 夫妻；一对", "49", False),
    ("cover", "/'kʌvə(r)/", "v. 覆盖 n. 封面", "19", False),
    ("cream", "/kriːm/", "n. 奶油；乳霜", "46", False),
    ("creative", "/kri'eɪtɪv/", "adj. 有创造力的", "67", False),
    ("creativity", "/ˌkriːeɪ'tɪvəti/", "n. 创造力", "66", False),
    ("crust", "/krʌst/", "n. 面包皮；外壳", "46", False),
    ("cure", "/kjʊə(r)/", "n. 疗法 v. 治愈", "65", False),
    ("cut sth in/into sth", "", "把……切成……", "42", False),
    ("cut up", "", "切碎", "42", False),

    # ===== D =====
    ("date", "/deɪt/", "n. 日期；约会 v. 约会", "79", False),
    ("dead", "/ded/", "adj. 死的；无生命的", "15", False),
    ("decorate", "/'dekəreɪt/", "v. 装饰；装潢", "19", False),
    ("deer", "/dɪə(r)/", "n. (pl. deer) 鹿", "9", False),
    ("depend", "/dɪ'pend/", "v. 依靠；取决于", "68", False),
    ("depend on/upon", "", "依靠；取决于", "68", False),
    ("describe", "/dɪ'skraɪb/", "v. 描述；形容", "17", False),
    ("design", "/dɪ'zaɪn/", "v. 设计 n. 设计", "58", False),
    ("designer", "/dɪ'zaɪnə(r)/", "n. 设计师", "52", False),
    ("detail", "/'diːteɪl/", "n. 细节；详情", "75", False),
    ("develop", "/dɪ'veləp/", "v. 发展；开发", "67", False),
    ("difference", "/'dɪfrəns/", "n. 差异；不同", "26", False),
    ("difficulty", "/'dɪfɪkəlti/", "n. 困难；难题", "75", False),
    ("direct", "/də'rekt; daɪ'rekt/", "adj. 直接的", "27", False),
    ("director", "/də'rektə(r); daɪ'rektə(r)/", "n. 导演；主任", "52", False),
    ("disappear", "/ˌdɪsə'pɪə(r)/", "v. 消失", "66", False),
    ("disappoint", "/ˌdɪsə'pɔɪnt/", "v. 使失望", "38", False),
    ("disappointed", "/ˌdɪsə'pɔɪntɪd/", "adj. 失望的", "36", False),
    ("disaster", "/dɪ'zɑːstə(r)/", "n. 灾难", "66", False),
    ("do with", "", "处理；对付", "43", False),
    ("draw to a close", "", "接近尾声", "59", False),
    ("dream", "/driːm/", "n. 梦想 v. 做梦；梦想", "45", False),
    ("drop sb a line", "", "给某人写封短信", "75", False),
    ("during", "/'djʊərɪŋ/", "prep. 在……期间", "6", False),

    # ===== E =====
    ("easily", "/'iːzəli/", "adv. 容易地", "6", False),
    ("ecosystem", "/'iːkəʊsɪstəm/", "n. 生态系统", "36", False),
    ("education", "/ˌedʒu'keɪʃn/", "n. 教育", "64", False),
    ("efficient", "/ɪ'fɪʃnt/", "adj. 高效的", "63", False),
    ("emergency", "/ɪ'mɜːdʒənsi/", "n. 紧急情况", "66", False),
    ("emotional", "/ɪ'məʊʃənl/", "adj. 情绪的；情感的", "66", False),
    ("emotional intelligence", "", "情商", "66", False),
    ("energetic", "/ˌenə'dʒetɪk/", "adj. 精力充沛的", "59", False),
    ("engineer", "/ˌendʒɪ'nɪə(r)/", "n. 工程师", "52", False),
    ("especially", "/ɪ'speʃəli/", "adv. 尤其；特别", "3", False),
    ("essay", "/'eseɪ/", "n. 文章；短文", "53", False),
    ("event", "/ɪ'vent/", "n. 事件；活动", "79", False),
    ("everywhere", "/'evriweə(r)/", "adv., pron. & conj. 到处", "66", False),
    ("except", "/ɪk'sept/", "prep. 除……之外", "39", False),
    ("exchange", "/ɪks'tʃeɪndʒ/", "v. & n. 交换；交流", "28", False),
    ("expect", "/ɪk'spekt/", "v. 期望；预计", "28", False),
    ("expert", "/'ekspɜːt/", "n. 专家 adj. 熟练的", "66", False),
    ("expression", "/ɪk'spreʃn/", "n. 表达；表情", "74", False),

    # ===== F =====
    ("face to face", "", "面对面地", "72", False),
    ("face-to-face", "", "adj. 面对面的", "73", False),
    ("fact", "/fækt/", "n. 事实；真相", "25", False),
    ("fail", "/feɪl/", "v. 失败；未能做到", "57", False),
    ("familiar", "/fə'mɪliə(r)/", "adj. 熟悉的", "16", False),
    ("fantastic", "/fæn'tæstɪk/", "adj. 极好的；了不起的", "3", False),
    ("faraway", "/'fɑːrəweɪ/", "adj. 遥远的", "8", False),
    ("fashion", "/'fæʃn/", "n. 时尚；时装", "52", False),
    ("feel free (to do sth)", "", "尽管（做某事）", "34", False),
    ("fight", "/faɪt/", "n. 打斗；斗争 v. (fought) 打架；战斗", "6", False),
    ("fight against sb/sth", "", "与……作斗争", "6", False),
    ("fill ... with ...", "", "用……装满……", "46", False),
    ("final", "/'faɪnl/", "adj. 最后的 n. 决赛", "58", False),
    ("find out", "", "查明；弄清", "76", False),
    ("fireman", "/'faɪəmən/", "n. (pl. firemen) 消防员", "52", False),
    ("flour", "/'flaʊə(r)/", "n. 面粉", "42", False),
    ("flute", "/fluːt/", "n. 长笛", "22", False),
    ("folding", "/'fəʊldɪŋ/", "adj. 可折叠的", "33", False),
    ("folding fan", "", "折扇", "33", False),
    ("for this reason", "", "因此", "36", False),
    ("forget", "/fə'ɡet/", "v. (forgot) 忘记", "6", False),
    ("forgetful", "/fə'ɡetfl/", "adj. 健忘的", "8", False),
    ("form", "/fɔːm/", "v. 形成 n. 形式；表格", "59", False),
    ("freshly", "/'freʃli/", "adv. 刚刚；新近", "17", False),
    ("friendship", "/'frendʃɪp/", "n. 友谊", "27", False),
    ("frog", "/frɒɡ/", "n. 青蛙", "35", False),
    ("futurist", "/'fjuːtʃərɪst/", "n. 未来学家", "66", False),

    # ===== G =====
    ("German", "/'dʒɜːmən/", "n. 德语；德国人 adj. 德国的", "68", False),
    ("get together", "", "聚会；聚集", "7", False),
    ("ginkgo", "/'ɡɪŋkɡəʊ/", "n. 银杏", "35", False),
    ("give sb a lift", "", "让某人搭车", "14", False),
    ("glue", "/ɡluː/", "n. 胶水 v. 粘贴", "19", False),
    ("go boating", "", "去划船", "45", False),
    ("go shopping", "", "去购物", "14", False),
    ("goodness", "/'ɡʊdnəs/", "n. 善良；美德", "33", False),
    ("guest", "/ɡest/", "n. 客人；宾客", "66", False),
    ("guide", "/ɡaɪd/", "n. 导游；指南 v. 引导", "5", False),

    # ===== H =====
    ("hang up", "", "挂断电话", "12", False),
    ("happiness", "/'hæpinəs/", "n. 快乐；幸福", "38", False),
    ("hard-working", "/ˌhɑːd 'wɜːkɪŋ/", "adj. 勤奋的", "22", False),
    ("have (...) to do with sb/sth", "", "与……有关", "56", False),
    ("have sth in common", "", "有共同之处", "24", False),
    ("health", "/helθ/", "n. 健康", "56", False),
    ("healthily", "/'helθɪli/", "adv. 健康地", "56", False),
    ("heat", "/hiːt/", "v. 加热 n. 热；热量", "43", False),
    ("honest", "/'ɒnɪst/", "adj. 诚实的", "27", False),
    ("honey", "/'hʌni/", "n. 蜂蜜", "36", False),
    ("honeycomb", "/'hʌnikəʊm/", "n. 蜂巢", "36", False),
    ("honour", "/'ɒnə(r)/", "n. (= honor) 荣誉 v. 尊敬", "79", False),
    ("host", "/həʊst/", "n. 主人；主持人 v. 主办", "46", False),
    ("hostess", "/'həʊstəs/", "n. 女主人；女主持人", "46", False),
    ("hot and sour soup", "", "酸辣汤", "44", False),
    ("hotel", "/həʊ'tel/", "n. 旅馆；酒店", "5", False),
    ("human", "/'hjuːmən/", "n. 人 adj. 人的；人类的", "37", False),
    ("humour", "/'hjuːmə(r)/", "n. (= humor) 幽默", "27", False),
    ("hunt", "/hʌnt/", "n. 打猎 v. 狩猎；搜寻", "14", False),

    # ===== I =====
    ("imagine", "/ɪ'mædʒɪn/", "v. 想象；设想", "36", False),
    ("impolite", "/ˌɪmpə'laɪt/", "adj. 不礼貌的", "76", False),
    ("importance", "/ɪm'pɔːtns/", "n. 重要性", "37", False),
    ("impossible", "/ɪm'pɒsəbl/", "adj. 不可能的", "67", False),
    ("in fact", "", "事实上；实际上", "36", False),
    ("in order to", "", "为了", "36", False),
    ("in person", "", "亲自", "73", False),
    ("in the sun", "", "在阳光下", "8", False),
    ("industry", "/'ɪndəstri/", "n. 工业；行业", "66", False),
    ("influence", "/'ɪnfluəns/", "v. 影响 n. 影响", "66", False),
    ("ingredient", "/ɪn'ɡriːdiənt/", "n. 原料；成分", "44", False),
    ("instruction", "/ɪn'strʌkʃn/", "n. (pl.) 指示；用法说明", "44", False),
    ("intelligence", "/ɪn'telɪdʒəns/", "n. 智力；智能", "66", False),
    ("interest", "/'ɪntrəst/", "n. 兴趣 v. 使感兴趣", "26", False),
    ("introduce", "/ˌɪntrə'djuːs/", "v. 介绍；引进", "57", False),
    ("invite", "/ɪn'vaɪt/", "v. 邀请", "12", False),
    ("island", "/'aɪlənd/", "n. 岛", "49", False),
    ("item", "/'aɪtəm/", "n. 物品；项目", "48", False),

    # ===== J =====
    ("joke", "/dʒəʊk/", "n. 玩笑 v. 开玩笑", "16", False),
    ("journey", "/'dʒɜːni/", "n. 旅行；旅程", "16", False),
    ("joy", "/dʒɔɪ/", "n. 欢乐；喜悦", "18", False),

    # ===== K =====
    ("keep (...) away from ...", "", "使……远离……", "72", False),
    ("keep on doing sth", "", "继续做某事", "56", False),
    ("kg", "", "n. (= kilogram) 千克", "53", False),
    ("km", "", "n. (= kilometre) 千米", "25", False),

    # ===== L =====
    ("land", "/lænd/", "n. 陆地；土地 v. 着陆", "35", False),
    ("landscape", "/'lændskeɪp/", "n. 风景；景色", "2", False),
    ("last but not least", "", "最后但同样重要的", "59", False),
    ("law", "/lɔː/", "n. 法律；法规", "54", False),
    ("lawyer", "/'lɔːjə(r)/", "n. 律师", "54", False),
    ("lazy", "/'leɪzi/", "adj. 懒惰的", "54", False),
    ("least", "/liːst/", "adv. & pron. 最少", "57", False),
    ("lend (sb) a hand", "", "帮助（某人）", "46", False),
    ("length", "/leŋθ/", "n. 长度", "29", False),
    ("less", "/les/", "adj. 较少的 adv. 较少地 pron. 较少", "64", False),
    ("lift", "/lɪft/", "n. 电梯；搭车 v. 举起", "27", False),
    ("line", "/laɪn/", "n. 线；行；台词", "14", False),
    ("lining", "/'laɪnɪŋ/", "n. 衬里", "29", False),
    ("listener", "/'lɪsənə(r)/", "n. 听众", "76", False),
    ("literature", "/'lɪtrətʃə(r)/", "n. 文学", "56", False),
    ("lively", "/'laɪvli/", "adj. 活泼的；生动的", "39", False),
    ("living room", "", "客厅", "12", False),
    ("local", "/'ləʊkl/", "adj. 当地的 n. 本地人", "78", False),
    ("look for", "", "寻找", "72", False),
    ("lotus", "/'ləʊtəs/", "n. 莲花", "9", False),
    ("loud", "/laʊd/", "adv. 大声地 adj. 大声的", "35", False),
    ("low", "/ləʊ/", "adv. 低 adj. 低的 n. 低点", "35", False),
    ("luggage", "/'lʌɡɪdʒ/", "n. 行李", "16", False),

    # ===== M =====
    ("make a mistake", "", "犯错误", "27", False),
    ("make sure", "", "确保；查明", "53", False),
    ("make up (with sb)", "", "（与某人）和解", "73", False),
    ("mash", "/mæʃ/", "v. 捣碎；捣烂", "42", False),
    ("mashed potatoes", "", "土豆泥", "42", False),
    ("matter", "/'mætə(r)/", "v. 要紧 n. 事情；问题", "22", False),
    ("meaning", "/'miːnɪŋ/", "n. 意义；含义", "17", False),
    ("medical", "/'medɪkl/", "adj. 医学的；医疗的", "68", False),
    ("medium", "/'miːdiəm/", "n. (pl. media) 媒介 adj. 中等的", "78", False),
    ("meeting", "/'miːtɪŋ/", "n. 会议；会面", "75", False),
    ("memory", "/'meməri/", "n. 记忆；回忆", "46", False),
    ("mention", "/'menʃn/", "v. 提到；提及", "66", False),
    ("mess", "/mes/", "n. 混乱；脏乱", "75", False),
    ("metre", "/'miːtə(r)/", "n. (= meter) 米", "28", False),
    ("metro", "/'metrəʊ/", "n. 地铁（系统）", "7", False),
    ("might", "/maɪt/", "modal v. 可能；也许", "5", False),
    ("mini-goal", "/'mɪni ɡəʊl/", "n. 小目标", "56", False),
    ("mirror", "/'mɪrə(r)/", "n. 镜子", "26", False),
    ("miss", "/mɪs/", "v. 错过；想念", "55", False),
    ("misunderstanding", "/ˌmɪsʌndə'stændɪŋ/", "n. 误解", "78", False),
    ("mix", "/mɪks/", "v. 混合 n. 混合物", "43", False),
    ("mix ... with ...", "", "把……与……混合", "43", False),
    ("mixture", "/'mɪkstʃə(r)/", "n. 混合物", "46", False),
    ("mm", "", "n. (= millimetre) 毫米", "25", False),
    ("mm/m", "", "interj. (= mmm) 嗯（表示思考等）", "16", False),
    ("moss", "/mɒs/", "n. 苔藓", "32", False),
    ("move on (to sth)", "", "继续前进（到……）", "76", False),
    ("movie", "/'muːvi/", "n. 电影", "15", False),
    ("mushroom", "/'mʌʃrʊm/", "n. 蘑菇", "38", False),
    ("musician", "/mju'zɪʃn/", "n. 音乐家", "52", False),
    ("myself", "/maɪ'self/", "pron. 我自己", "5", False),

    # ===== N =====
    ("nervous", "/'nɜːvəs/", "adj. 紧张的；焦虑的", "76", False),
    ("nod", "/nɒd/", "v. & n. 点头", "16", False),
    ("no matter", "", "不管；不论", "17", False),
    ("noon", "/nuːn/", "n. 中午", "6", False),
    ("note", "/nəʊt/", "n. 笔记；便条 v. 注意", "15", False),
    ("nothing", "/'nʌθɪŋ/", "pron. 没有什么；没有东西", "3", False),
    ("nothing but", "", "只有；只不过", "5", False),
    ("novel", "/'nɒvl/", "n. 小说", "26", False),

    # ===== O =====
    ("ocean", "/'əʊʃn/", "n. 海洋", "39", False),
    ("offer", "/'ɒfə(r)/", "v. 提供；提出 n. 提议", "76", False),
    ("oil", "/ɔɪl/", "n. 油；石油", "42", False),
    ("one by one", "", "一个一个地", "49", False),
    ("opening", "/'əʊpnɪŋ/", "adj. 开始的 n. 开始；开口", "79", False),
    ("opinion", "/ə'pɪnjən/", "n. 意见；看法", "27", False),
    ("opportunity", "/ˌɒpə'tjuːnəti/", "n. 机会", "79", False),
    ("organized", "/'ɔːɡənaɪzd/", "adj. (= organised) 有条理的", "56", False),
    ("outer", "/'aʊtə(r)/", "adj. 外部的；外面的", "62", False),
    ("outer space", "", "外太空", "62", False),
    ("outgoing", "/ˌaʊt'ɡəʊɪŋ/", "adj. 外向的", "22", False),
    ("oven", "/'ʌvn/", "n. 烤箱", "42", False),

    # ===== P =====
    ("pack", "/pæk/", "v. 打包；包装", "12", False),
    ("pack up", "", "收拾行装", "12", False),
    ("painter", "/'peɪntə(r)/", "n. 画家", "54", False),
    ("palace", "/'pæləs/", "n. 宫殿", "16", False),
    ("pan", "/pæn/", "n. 平底锅", "43", False),
    ("pancake", "/'pænkeɪk/", "n. 煎饼；薄饼", "45", False),
    ("paper-cut", "/'peɪpəkʌt/", "n. 剪纸", "19", False),
    ("paragraph", "/'pærəɡrɑːf/", "n. 段落", "57", False),
    ("partner", "/'pɑːtnə(r)/", "n. 伙伴；搭档", "64", False),
    ("pass", "/pɑːs/", "v. 通过；传递 n. 通行证", "65", False),
    ("passport", "/'pɑːspɔːt/", "n. 护照", "8", False),
    ("pauper", "/'pɔːpə(r)/", "n. 穷人；贫民", "28", False),
    ("pay", "/peɪ/", "v. (paid) 支付；付款 n. 工资", "76", False),
    ("pay attention (to ...)", "", "注意（……）", "76", False),
    ("pea", "/piː/", "n. 豌豆", "38", False),
    ("peace", "/piːs/", "n. 和平；安宁", "6", False),
    ("peony", "/'piːəni/", "n. 牡丹", "35", False),
    ("pepper", "/'pepə(r)/", "n. 胡椒；辣椒", "42", False),
    ("per", "/pə(r); pɜː(r)/", "prep. 每；每一", "25", False),
    ("per cent", "/pə 'sent/", "n. (= percent) 百分之……", "25", False),
    ("perform", "/pə'fɔːm/", "v. 表演；执行", "22", False),
    ("perhaps", "/pə'hæps; præps/", "adv. 也许；可能", "17", False),
    ("personal", "/'pɜːsənl/", "adj. 个人的；私人的", "76", False),
    ("personality", "/ˌpɜːsə'næləti/", "n. 个性；性格", "24", False),
    ("photographer", "/fə'tɒɡrəfə(r)/", "n. 摄影师", "54", False),
    ("photography", "/fə'tɒɡrəfi/", "n. 摄影", "56", False),
    ("physical", "/'fɪzɪkl/", "adj. 身体的；物理的", "56", False),
    ("pie", "/paɪ/", "n. 馅饼", "46", False),
    ("pilot", "/'paɪlət/", "n. 飞行员", "35", False),
    ("plan", "/plæn/", "v. 计划 n. 计划", "14", False),
    ("planet", "/'plænɪt/", "n. 行星", "36", False),
    ("plate", "/pleɪt/", "n. 盘子", "17", False),
    ("play a part (in sth)", "", "（在……中）起作用", "36", False),
    ("play a role (in)", "", "在……中扮演角色；起作用", "38", False),
    ("pleasant", "/'pleznt/", "adj. 令人愉快的", "25", False),
    ("pleasure", "/'pleʒə(r)/", "n. 快乐；乐趣", "76", False),
    ("point", "/pɔɪnt/", "n. 观点；要点 v. 指", "76", False),
    ("pollen", "/'pɒlən/", "n. 花粉", "36", False),
    ("pollination", "/ˌpɒlə'neɪʃn/", "n. 授粉", "36", False),
    ("popular", "/'pɒpjələ(r)/", "adj. 受欢迎的；流行的", "33", False),
    ("population", "/ˌpɒpju'leɪʃn/", "n. 人口", "25", False),
    ("positive", "/'pɒzətɪv/", "adj. 积极的；正面的", "36", False),
    ("possible", "/'pɒsəbl/", "adj. 可能的", "56", False),
    ("poster", "/'pəʊstə(r)/", "n. 海报", "19", False),
    ("pour sth into sth", "", "把……倒入……", "42", False),
    ("prediction", "/prɪ'dɪkʃn/", "n. 预测", "62", False),
    ("prefer", "/prɪ'fɜː(r)/", "v. 更喜欢", "73", False),
    ("pretty", "/'prɪti/", "adj. 漂亮的 adv. 相当", "45", False),
    ("prince", "/prɪns/", "n. 王子", "54", False),
    ("prize", "/praɪz/", "n. 奖品；奖赏", "23", False),
    ("probably", "/'prɒbəbli/", "adv. 很可能；大概", "56", False),
    ("professor", "/prə'fesə(r)/", "n. 教授", "73", False),
    ("protect", "/prə'tekt/", "v. 保护", "36", False),
    ("province", "/'prɒvɪns/", "n. 省", "35", False),
    ("public", "/'pʌblɪk/", "adj. 公共的 n. 公众", "68", False),
    ("pull", "/pʊl/", "v. & n. 拉；拖", "16", False),
    ("pumpkin", "/'pʌmpkɪn/", "n. 南瓜", "46", False),
    ("push-up", "/'pʊʃʌp/", "n. 俯卧撑", "59", False),
    ("put sth back", "", "把……放回", "43", False),
    ("put out", "", "熄灭；伸出", "58", False),

    # ===== Q =====
    ("quality", "/'kwɒləti/", "n. 质量；品质 adj. 优质的", "67", False),

    # ===== R =====
    ("rainbow", "/'reɪnbəʊ/", "n. 彩虹", "5", False),
    ("rainfall", "/'reɪnfɔːl/", "n. 降雨量", "25", False),
    ("reach", "/riːtʃ/", "v. 到达；伸出", "29", False),
    ("reach for", "", "伸手去够", "29", False),
    ("ready", "/'redi/", "adj. 准备好的 adv. 预先", "5", False),
    ("ready to do sth", "", "准备好做某事", "5", False),
    ("reasonable", "/'riːznəbl/", "adj. 合理的", "77", False),
    ("recipe", "/'resəpi/", "n. 食谱；配方", "46", False),
    ("redwood", "/'redwʊd/", "n. 红杉", "32", False),
    ("refrigerator", "/rɪ'frɪdʒəreɪtə(r)/", "n. (= fridge) 冰箱", "66", False),
    ("regular", "/'reɡjələ(r)/", "adj. 定期的；常规的", "8", False),
    ("rehearsal", "/rɪ'hɜːsl/", "n. 排练", "72", False),
    ("relationship", "/rɪ'leɪʃnʃɪp/", "n. 关系", "59", False),
    ("remind", "/rɪ'maɪnd/", "v. 提醒；使想起", "6", False),
    ("replace", "/rɪ'pleɪs/", "v. 代替；更换", "66", False),
    ("reply", "/rɪ'plaɪ/", "n. & v. 回答；回复", "79", False),
    ("research", "/rɪ'sɜːtʃ/", "n. & v. 研究", "66", False),
    ("researcher", "/rɪ'sɜːtʃə(r)/", "n. 研究员", "66", False),
    ("resolution", "/ˌrezə'luːʃn/", "n. 决心；决议", "56", False),
    ("reunion", "/ˌriː'juːniən/", "n. 团聚；重逢", "75", False),
    ("right away", "", "立刻；马上", "75", False),
    ("robotics", "/rəʊ'bɒtɪks/", "n. 机器人技术", "66", False),
    ("role", "/rəʊl/", "n. 角色；作用", "38", False),
    ("rose", "/rəʊz/", "n. 玫瑰", "35", False),
    ("rubbish", "/'rʌbɪʃ/", "n. 垃圾", "15", False),
    ("run low (on sth)", "", "（某物）快用完了", "66", False),
    ("Russian", "/'rʌʃn/", "adj. 俄罗斯的 n. 俄语；俄罗斯人", "6", False),

    # ===== S =====
    ("scarf", "/skɑːf/", "n. 围巾", "5", False),
    ("scenery", "/'siːnəri/", "n. 风景；景色", "5", False),
    ("sci-fi", "/'saɪ faɪ/", "n. (= science fiction) 科幻小说", "62", False),
    ("scissors", "/'sɪzəz/", "n. (pl.) 剪刀", "19", False),
    ("secret", "/'siːkrət/", "n. 秘密 adj. 秘密的", "47", False),
    ("self-improvement", "/ˌselfɪm'pruːvmənt/", "n. 自我提升", "56", False),
    ("sense", "/sens/", "n. 感觉；感官 v. 感觉到", "27", False),
    ("sentence", "/'sentəns/", "n. 句子", "79", False),
    ("separate", "/'seprət/", "adj. 分开的 v. 分开；分离", "49", False),
    ("serious", "/'sɪəriəs/", "adj. 严肃的；严重的", "24", False),
    ("seriously", "/'sɪəriəsli/", "adv. 严肃地；认真地", "75", False),
    ("service", "/'sɜːvɪs/", "n. 服务", "66", False),
    ("several", "/'sevrəl/", "pron. 几个；数个", "16", False),
    ("shall", "/ʃæl; ʃəl/", "modal v. (should) 将要；应该", "65", False),
    ("share sth with sb", "", "与某人分享某物", "16", False),
    ("shoot", "/ʃuːt/", "n. 嫩芽 v. (shot) 射击；拍摄", "33", False),
    ("show interest in sth", "", "对……表现出兴趣", "76", False),
    ("show sb around", "", "带某人参观", "72", False),
    ("shy", "/ʃaɪ/", "adj. 害羞的", "22", False),
    ("sick", "/sɪk/", "adj. 生病的；恶心的", "6", False),
    ("sign", "/saɪn/", "n. 标志；迹象 v. 签名", "72", False),
    ("silk", "/sɪlk/", "n. 丝绸", "5", False),
    ("silver", "/'sɪlvə(r)/", "adj. 银的 n. 银", "29", False),
    ("silver lining", "", "一线希望", "29", False),
    ("similarity", "/ˌsɪmə'lærəti/", "n. 相似之处", "27", False),
    ("simple", "/'sɪmpl/", "adj. 简单的", "43", False),
    ("sincere", "/sɪn'sɪə(r)/", "adj. 真诚的", "76", False),
    ("sincerely", "/sɪn'sɪəli/", "adv. 真诚地", "79", False),
    ("situation", "/ˌsɪtʃu'eɪʃn/", "n. 情况；形势", "29", False),
    ("sky", "/skaɪ/", "n. 天空", "5", False),
    ("slice", "/slaɪs/", "n. 片；薄片 v. 切片", "48", False),
    ("slim", "/slɪm/", "adj. 苗条的", "25", False),
    ("smell", "/smel/", "v. 闻；嗅 n. 气味", "18", False),
    ("social", "/'səʊʃl/", "adj. 社会的；社交的", "24", False),
    ("social media", "", "社交媒体", "78", False),
    ("solve", "/sɒlv/", "v. 解决", "22", False),
    ("somewhere", "/'sʌmweə(r)/", "adv. 在某处 pron. 某处", "5", False),
    ("sort", "/sɔːt/", "v. 分类；整理 n. 种类", "12", False),
    ("sour", "/'saʊə(r)/", "adj. 酸的", "44", False),
    ("spaghetti", "/spə'ɡeti/", "n. 意大利面", "48", False),
    ("spare", "/speə(r)/", "adj. 空闲的 v. 抽出", "23", False),
    ("spare time", "", "空闲时间", "23", False),
    ("speaker", "/'spiːkə(r)/", "n. 发言人；演讲者", "72", False),
    ("speech", "/spiːtʃ/", "n. 演讲；发言", "73", False),
    ("spoon", "/spuːn/", "n. (= spoonful) 一勺的量", "48", False),
    ("square", "/skweə(r)/", "n. 广场；正方形 adj. 正方形的", "6", False),
    ("station", "/'steɪʃn/", "n. 车站；站", "7", False),
    ("steamed chicken soup", "", "清蒸鸡汤", "3", False),
    ("steamed fish", "", "清蒸鱼", "44", False),
    ("stick", "/stɪk/", "v. (stuck) 粘贴；坚持 n. 棍子", "56", False),
    ("stick to sth", "", "坚持某事", "56", False),
    ("stir-fry", "/'stɜːfraɪ/", "v. 翻炒", "43", False),
    ("store", "/stɔː(r)/", "v. 储存 n. 商店", "36", False),
    ("straightforward", "/ˌstreɪt'fɔːwəd/", "adj. 简单明了的", "27", False),
    ("strange", "/streɪndʒ/", "adj. 奇怪的；陌生的", "2", False),
    ("stranger", "/'streɪndʒə(r)/", "n. 陌生人", "76", False),
    ("strength", "/streŋθ/", "n. 力量；优点", "78", False),
    ("surprised", "/sə'praɪzd/", "adj. 惊讶的", "9", False),
    ("surely", "/'ʃʊəli/", "adv. 想必；无疑", "76", False),
    ("sweetness", "/'swiːtnəs/", "n. 甜蜜；甜味", "46", False),
    ("system", "/'sɪstəm/", "n. 系统", "63", False),

    # ===== T =====
    ("tablespoon", "/'teɪblspuːn/", "n. 一汤匙的量", "42", False),
    ("take a walk", "", "散步", "35", False),
    ("take notes", "", "记笔记", "15", False),
    ("take over", "", "接管；接手", "62", False),
    ("take place", "", "发生；举行", "79", False),
    ("take sb's breath away", "", "令人叹为观止", "3", False),
    ("take up", "", "开始从事；占据", "56", False),
    ("task", "/tɑːsk/", "n. 任务", "68", False),
    ("tear", "/tɪə(r)/", "n. 眼泪", "6", False),
    ("technology", "/tek'nɒlədʒi/", "n. 技术", "63", False),
    ("text", "/tekst/", "n. 文本；课文 v. 发短信", "17", False),
    ("text message", "", "短信", "72", False),
    ("thanks to", "", "幸亏；由于", "27", False),
    ("the movies", "", "电影院；电影", "15", False),
    ("thousands of", "", "成千上万的", "6", False),
    ("tiny", "/'taɪni/", "adj. 极小的", "39", False),
    ("ticket", "/'tɪkɪt/", "n. 票", "62", False),
    ("tip", "/tɪp/", "n. 小费；提示 v. 给……小费", "76", False),
    ("title", "/'taɪtl/", "n. 标题；头衔", "37", False),
    ("ton", "/tʌn/", "n. 吨", "38", False),
    ("tool", "/tuːl/", "n. 工具", "33", False),
    ("topic", "/'tɒpɪk/", "n. 话题；主题", "64", False),
    ("touch", "/tʌtʃ/", "v. 触摸；感动 n. 接触", "29", False),
    ("towards", "/tə'wɔːdz; tɔːrdz/", "prep. (= toward) 向；朝", "5", False),
    ("tower", "/'taʊə(r)/", "n. 塔", "8", False),
    ("town", "/taʊn/", "n. 城镇", "3", False),
    ("traffic", "/'træfɪk/", "n. 交通；运输", "63", False),
    ("training", "/'treɪnɪŋ/", "n. 训练", "75", False),
    ("transport", "/'trænspɔːt/", "n. 运输；交通系统 v. 运输", "63", False),
    ("treasure", "/'treʒə(r)/", "n. 财宝；珍宝 v. 珍视", "14", False),
    ("treasure hunt", "", "寻宝", "14", False),
    ("trust", "/trʌst/", "n. & v. 信任；相信", "78", False),
    ("try one's best", "", "尽力", "53", False),
    ("turn around", "", "转身；转向", "9", False),

    # ===== U =====
    ("university", "/ˌjuːnɪ'vɜːsəti/", "n. 大学", "45", False),
    ("until", "/ən'tɪl/", "prep. 直到……为止", "15", False),
    ("up to", "", "多达；取决于", "35", False),

    # ===== V =====
    ("vacation", "/və'keɪʃn/", "n. 假期；休假", "2", False),
    ("valuable", "/'væljuəbl/", "adj. 有价值的；宝贵的", "68", False),
    ("victory", "/'vɪktəri/", "n. 胜利", "6", False),
    ("video", "/'vɪdiəʊ/", "n. 视频 v. 录制", "63", False),
    ("visible", "/'vɪzəbl/", "adj. 可见的；明显的", "46", False),

    # ===== W =====
    ("wallet", "/'wɒlɪt/", "n. 钱包", "65", False),
    ("warm up", "", "热身；变暖", "46", False),
    ("weigh", "/weɪ/", "v. 称重；重量为", "35", False),
    ("whenever", "/wen'evə(r)/", "adv. & conj. 无论何时", "47", False),
    ("wherever", "/weər'evə(r)/", "adv. & conj. 无论哪里", "17", False),
    ("wife", "/waɪf/", "n. (pl. wives) 妻子", "49", False),
    ("wing", "/wɪŋ/", "n. 翅膀", "35", False),
    ("winner", "/'wɪnə(r)/", "n. 获胜者", "65", False),
    ("wisely", "/'waɪzli/", "adv. 明智地", "56", False),
    ("without", "/wɪ'ðaʊt/", "prep. 没有；无", "36", False),
    ("worry about", "", "担心", "33", False),
    ("worse", "/wɜːs/", "adj. (bad的比较级) 更糟的 adv. 更糟地", "62", False),
    ("writer", "/'raɪtə(r)/", "n. 作家", "17", False),

    # ===== Y =====
    ("yeah", "/jeə/", "interj. 是的；对", "74", False),
    ("yet", "/jet/", "adv. 还未 conj. 然而", "13", False),
    ("yourself", "/jɔː'self/", "pron. (pl. yourselves) 你自己", "17", False),
]

def generate_md(vocab, title, output_path):
    lines = [f"# {title}\n"]
    lines.append("> 注：加 `*` 的词为《义务教育英语课程标准（2022年版）》中的二级词。\n")
    lines.append("---\n")
    import string
    for letter in string.ascii_uppercase:
        group = [(w, p, c, pg, k) for w, p, c, pg, k in vocab
                 if w.lstrip('*').upper().startswith(letter)]
        if group:
            lines.append(f"## {letter}\n")
            lines.append("| 单词 | 音标 | 释义 | 页码 |")
            lines.append("|------|------|------|------|")
            for w, p, c, pg, k in group:
                phonetic = p if p else ""
                lines.append(f"| {w} | {phonetic} | {c} | p. {pg} |")
            lines.append("")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return len(vocab)

out = os.path.join(BASE, '八年级上册词汇表.md')
n = generate_md(C2A_VOCAB, "人教版 PEP 八年级上册词汇表", out)
key_count = sum(1 for _,_,_,_,k in C2A_VOCAB if k)
print(f"Generated: {out}")
print(f"Total: {n} entries (key: {key_count}, non-key: {n - key_count})")