#!/usr/bin/env python3
"""Generate 八年级下册词汇表.md from OCR-extracted vocabulary."""
import os

BASE = '/Users/allen/Downloads/人教版(PEP)'

C2B_VOCAB = [
    # ===== A =====
    ("a bit", "", "稍微；有点儿", "26", False),
    ("a good read", "", "一本好的读物", "61", False),
    ("above", "/ə'bʌv/", "prep. & adv. 在……上面", "36", False),
    ("ache", "/eɪk/", "n. & v. 疼痛", "13", False),
    ("achievement", "/ə'tʃiːvmənt/", "n. 成就", "6", False),
    ("active", "/'æktɪv/", "adj. 积极的；活跃的", "74", False),
    ("adult", "/'ædʌlt; ə'dʌlt/", "n. 成年人 adj. 成年的", "76", False),
    ("adventure", "/əd'ventʃə(r)/", "n. 冒险；历险", "62", False),
    ("advertisement", "/əd'vɜːtɪsmənt/", "n. (= ad) 广告", "79", False),
    ("advise", "/əd'vaɪz/", "v. 建议；劝告", "22", False),
    ("aid", "/eɪd/", "n. & v. 帮助；援助", "16", False),
    ("alarm", "/ə'lɑːm/", "n. 警报(器)；闹钟", "49", False),
    ("alarm clock", "", "闹钟", "49", False),
    ("alien", "/'eɪliən/", "n. 外星人", "62", False),
    ("alive", "/ə'laɪv/", "adj. 活着的；在世的", "39", False),
    ("all of a sudden", "", "突然", "49", False),
    ("all smiles", "", "满脸笑容", "26", False),
    ("allergic", "/ə'lɜːdʒɪk/", "adj. 过敏的", "19", False),
    ("allow", "/ə'laʊ/", "v. 允许；准许", "6", False),
    ("ambition", "/æm'bɪʃn/", "n. 雄心；抱负", "37", False),
    ("American", "/ə'merɪkən/", "adj. 美国的 n. 美国人", "69", False),
    ("anger", "/'æŋɡə(r)/", "n. 愤怒", "22", False),
    ("anybody", "/'enibɒdi/", "pron. 任何人", "29", False),
    ("apologize", "/ə'pɒlədʒaɪz/", "v. (= apologise) 道歉", "27", False),
    ("army", "/'ɑːmi/", "n. 军队", "75", False),
    ("as a result", "", "结果", "49", False),
    ("as soon as", "", "一……就……", "47", False),
    ("as well", "", "也；还", "26", False),
    ("Asian", "/'eɪʒn; 'eɪʃn/", "adj. 亚洲的 n. 亚洲人", "58", False),
    ("at all costs", "", "不惜任何代价", "34", False),
    ("attack", "/ə'tæk/", "v. & n. 攻击；袭击", "62", False),
    ("attract", "/ə'trækt/", "v. 吸引", "38", False),
    ("au revoir", "", "再见（法语）", "57", False),
    ("audience", "/'ɔːdiəns/", "n. 观众；听众", "77", False),
    ("avoid", "/ə'vɔɪd/", "v. 避免；回避", "13", False),
    ("awake", "/ə'weɪk/", "adj. 醒着的", "28", False),
    ("award", "/ə'wɔːd/", "n. 奖；奖品", "24", False),

    # ===== B =====
    ("backache", "/'bækeɪk/", "n. 背痛", "12", False),
    ("badly", "/'bædli/", "adv. (worse; worst) 严重地", "17", False),
    ("bark", "/bɑːk/", "v. (狗)吠 n. 吠声", "76", False),
    ("base", "/beɪs/", "v. 以……为基础 n. 基础", "65", False),
    ("base sth on sth", "", "把……建立在……基础上", "65", False),
    ("basic", "/'beɪsɪk/", "adj. 基本的；基础的", "69", False),
    ("be about to", "", "即将；正要", "16", False),
    ("be hard on", "", "对……苛刻", "26", False),
    ("be used to", "", "习惯于", "55", False),
    ("beat", "/biːt/", "v. (beat; beaten) 打；击败 n. 节拍", "45", False),
    ("behave", "/bɪ'heɪv/", "v. 行为；表现", "28", False),
    ("below", "/bɪ'ləʊ/", "prep. & adv. 在……下面", "32", False),
    ("bit", "/bɪt/", "n. 一点儿", "26", False),
    ("bit by bit", "", "一点一点地", "36", False),
    ("bleed", "/bliːd/", "v. (bled) 流血", "18", False),
    ("blouse", "/blaʊz/", "n. 女式衬衫", "56", False),
    ("bone", "/bəʊn/", "n. 骨头", "69", False),
    ("bottom", "/'bɒtəm/", "n. 底部", "33", False),
    ("bow", "/baʊ/", "v. & n. 鞠躬", "52", False),
    ("brightness", "/'braɪtnəs/", "n. 亮度", "15", False),
    ("bruised", "/bruːzd/", "adj. 瘀伤的", "13", False),
    ("build-up", "/'bɪldʌp/", "n. 逐步增加", "67", False),
    ("bully", "/'bʊli/", "v. 欺凌 n. 恶霸", "28", False),
    ("bump", "/bʌmp/", "v. 碰撞 n. 肿块", "52", False),
    ("burn", "/bɜːn/", "v. (burnt) 燃烧；烧伤", "16", False),
    ("by the time", "", "到……的时候", "49", False),

    # ===== C =====
    ("cage", "/keɪdʒ/", "n. 笼子", "73", False),
    ("calligraphy", "/kə'lɪɡrəfi/", "n. 书法", "2", False),
    ("can", "/kæn/", "n. (金属)罐头", "72", False),
    ("careless", "/'keələs/", "adj. 粗心的", "13", False),
    ("catch fire", "", "着火", "16", False),
    ("changeable", "/'tʃeɪndʒəbl/", "adj. 多变的", "36", False),
    ("charity", "/'tʃærəti/", "n. 慈善机构", "75", False),
    ("chat", "/tʃæt/", "v. & n. 聊天", "5", False),
    ("check", "/tʃek/", "v. 检查 n. 支票", "18", False),
    ("cheek", "/tʃiːk/", "n. 脸颊", "52", False),
    ("cheers", "/tʃɪəz/", "interj. 干杯；谢谢", "59", False),
    ("chopstick", "/'tʃɒpstɪk/", "n. (usually pl.) 筷子", "54", False),
    ("civilization", "/ˌsɪvəlaɪ'zeɪʃn/", "n. (= civilisation) 文明", "34", False),
    ("clear", "/klɪə(r)/", "adj. 清楚的 v. 清理", "15", False),
    ("clear the air", "", "消除误会", "23", False),
    ("clearly", "/'klɪəli/", "adv. 清楚地", "24", False),
    ("cliff", "/klɪf/", "n. 悬崖", "36", False),
    ("climax", "/'klaɪmæks/", "n. 高潮；顶点", "67", False),
    ("climber", "/'klaɪmə(r)/", "n. 攀登者", "36", False),
    ("coach", "/kəʊtʃ/", "n. 教练", "26", False),
    ("coast", "/kəʊst/", "n. 海岸", "39", False),
    ("coin", "/kɔɪn/", "n. 硬币", "6", False),
    ("come along", "", "出现；一起来", "74", False),
    ("come off", "", "脱落；举行", "43", False),
    ("completely", "/kəm'pliːtli/", "adv. 完全地", "78", False),
    ("condition", "/kən'dɪʃn/", "n. 条件；状况", "36", False),
    ("confused", "/kən'fjuːzd/", "adj. 困惑的", "52", False),
    ("confusing", "/kən'fjuːzɪŋ/", "adj. 令人困惑的", "54", False),
    ("congratulate", "/kən'ɡrætʃuleɪt/", "v. 祝贺", "58", False),
    ("consider", "/kən'sɪdə(r)/", "v. 考虑", "68", False),
    ("control", "/kən'trəʊl/", "v. & n. 控制", "22", False),
    ("coral", "/'kɒrəl/", "n. 珊瑚", "39", False),
    ("correct", "/kə'rekt/", "adj. 正确的", "58", False),
    ("correctly", "/kə'rektli/", "adv. 正确地", "58", False),
    ("cough", "/kɒf/", "n. & v. 咳嗽", "13", False),
    ("cross", "/krɒs/", "v. 穿过；交叉", "15", False),
    ("cubic", "/'kjuːbɪk/", "adj. 立方的", "35", False),
    ("cubic metre", "", "立方米", "35", False),
    ("cultural", "/'kʌltʃərəl/", "adj. 文化的", "55", False),
    ("curiosity", "/ˌkjʊəri'ɒsəti/", "n. 好奇心", "37", False),
    ("curious", "/'kjʊəriəs/", "adj. 好奇的", "38", False),
    ("curry", "/'kʌri/", "n. 咖喱", "53", False),
    ("custom", "/'kʌstəm/", "n. 习俗", "56", False),
    ("cut ... in half", "", "把……切成两半", "25", False),

    # ===== D =====
    ("dare", "/deə(r)/", "v. & modal v. 敢", "26", False),
    ("day by day", "", "一天天地", "66", False),
    ("deal", "/diːl/", "n. 交易 v. (dealt) 处理", "4", False),
    ("deal with", "", "处理；应付", "21", False),
    ("death", "/deθ/", "n. 死；死亡", "36", False),
    ("decision", "/dɪ'sɪʒn/", "n. 决定", "26", False),
    ("deep", "/diːp/", "adj. 深的", "28", False),
    ("defeat", "/dɪ'fiːt/", "v. 击败 n. 失败", "68", False),
    ("degree", "/dɪ'ɡriː/", "n. 度；学位", "36", False),
    ("dentist", "/'dentɪst/", "n. 牙医", "13", False),
    ("depth", "/depθ/", "n. 深度", "33", False),
    ("description", "/dɪ'skrɪpʃn/", "n. 描述", "14", False),
    ("desert", "/'dezət/", "n. 沙漠", "32", False),
    ("destroy", "/dɪ'strɔɪ/", "v. 破坏；摧毁", "69", False),
    ("detective", "/dɪ'tektɪv/", "n. 侦探", "62", False),
    ("determined", "/dɪ'tɜːmɪnd/", "adj. 坚定的", "36", False),
    ("development", "/dɪ'veləpmənt/", "n. 发展", "34", False),
    ("differently", "/'dɪfrəntli/", "adv. 不同地", "28", False),
    ("distance", "/'dɪstəns/", "n. 距离", "36", False),
    ("dive", "/daɪv/", "v. & n. 潜水；跳水", "33", False),
    ("do chores", "", "做家务", "42", False),
    ("donate", "/dəʊ'neɪt/", "v. 捐赠", "78", False),
    ("donation", "/dəʊ'neɪʃn/", "n. 捐赠", "73", False),
    ("doubt", "/daʊt/", "v. 怀疑 n. 疑虑", "69", False),
    ("dream of", "", "梦想；向往", "7", False),
    ("drought", "/draʊt/", "n. 干旱", "42", False),

    # ===== E =====
    ("earthquake", "/'ɜːθkweɪk/", "n. 地震", "42", False),
    ("eat out", "", "外出就餐", "17", False),
    ("effect", "/ɪ'fekt/", "n. 效果；影响", "67", False),
    ("effort", "/'efət/", "n. 努力", "78", False),
    ("elbow", "/'elbəʊ/", "n. 手肘", "54", False),
    ("elder", "/'eldə(r)/", "adj. 年长的", "78", False),
    ("elderly", "/'eldəli/", "adj. 上了年纪的", "72", False),
    ("embarrassed", "/ɪm'bærəst/", "adj. 尴尬的", "52", False),
    ("embarrassing", "/ɪm'bærəsɪŋ/", "adj. 令人尴尬的", "55", False),
    ("emotion", "/ɪ'məʊʃn/", "n. 情感；情绪", "21", False),
    ("enemy", "/'enəmi/", "n. 敌人", "68", False),
    ("enter", "/'entə(r)/", "v. 进入", "26", False),
    ("environment", "/ɪn'vaɪrənmənt/", "n. 环境", "15", False),
    ("etc.", "/et 'setərə/", "等等；诸如此类", "79", False),
    ("even though", "", "尽管；即使", "27", False),
    ("ever since", "", "自从", "76", False),
    ("everybody", "/'evribɒdi/", "pron. 每人；人人", "26", False),
    ("explorer", "/ɪk'splɔːrə(r)/", "n. 探险者", "37", False),
    ("express", "/ɪk'spres/", "v. 表达", "2", False),
    ("extinguisher", "/ɪk'stɪŋɡwɪʃə(r)/", "n. 灭火器", "16", False),

    # ===== F =====
    ("failure", "/'feɪljə(r)/", "n. 失败", "8", False),
    ("false", "/fɔːls/", "adj. 错误的；伪造的", "68", False),
    ("familiar with", "", "熟悉", "79", False),
    ("fantasy", "/'fæntəsi/", "n. 幻想", "62", False),
    ("fault", "/fɔːlt/", "n. 过错；缺点", "23", False),
    ("fear", "/fɪə(r)/", "n. & v. 害怕", "3", False),
    ("feel blue", "", "感到忧郁", "26", False),
    ("fever", "/'fiːvə(r)/", "n. 发烧", "13", False),
    ("fiction", "/'fɪkʃn/", "n. 小说", "62", False),
    ("firefighter", "/'faɪəfaɪtə(r)/", "n. 消防员", "48", False),
    ("first aid", "", "急救", "16", False),
    ("firstly", "/'fɜːstli/", "adv. 首先", "58", False),
    ("fist", "/fɪst/", "n. 拳头", "52", False),
    ("flame", "/fleɪm/", "n. 火焰", "16", False),
    ("flood", "/flʌd/", "n. 洪水 v. 淹没", "42", False),
    ("floodwater", "/'flʌdwɔːtə(r)/", "n. 洪水", "48", False),
    ("flu", "/fluː/", "n. 流感", "14", False),
    ("force", "/fɔːs/", "v. 强迫 n. 力量", "63", False),
    ("foreign", "/'fɒrən/", "adj. 外国的", "7", False),
    ("forgive", "/fə'ɡɪv/", "v. (forgave; forgiven) 原谅", "23", False),
    ("fork", "/fɔːk/", "n. 叉子", "53", False),
    ("formal", "/'fɔːml/", "adj. 正式的", "52", False),
    ("freshwater", "/'freʃwɔːtə(r)/", "adj. 淡水的", "38", False),
    ("from now on", "", "从现在起", "19", False),
    ("from time to time", "", "偶尔；有时", "28", False),
    ("froth", "/frɒθ/", "n. 泡沫", "46", False),
    ("fry", "/fraɪ/", "v. 油炸；油煎", "16", False),

    # ===== G =====
    ("gas", "/ɡæs/", "n. 气体；煤气", "13", False),
    ("gentle", "/'dʒentl/", "adj. 温和的", "59", False),
    ("gentleman", "/'dʒentlmən/", "n. (pl. gentlemen) 绅士", "76", False),
    ("get across", "", "使……被理解", "24", False),
    ("get along", "", "相处；进展", "57", False),
    ("get into", "", "进入；陷入", "5", False),
    ("get lost", "", "迷路", "64", False),
    ("get over", "", "克服；从……恢复", "3", False),
    ("get to one's feet", "", "站起来", "66", False),
    ("give it a go", "", "试一试", "5", False),
    ("give up", "", "放弃", "3", False),
    ("go a long way", "", "大有帮助", "57", False),
    ("go off", "", "(警报等)响起", "49", False),
    ("go on an outing", "", "去郊游", "5", False),
    ("go wrong", "", "出问题；出错", "27", False),
    ("guard", "/ɡɑːd/", "n. 守卫 v. 保卫", "46", False),

    # ===== H =====
    ("hand out", "", "分发", "78", False),
    ("happily", "/'hæpɪli/", "adv. 快乐地", "16", False),
    ("harm", "/hɑːm/", "n. & v. 伤害", "17", False),
    ("harmful", "/'hɑːmfl/", "adj. 有害的", "18", False),
    ("headache", "/'hedeɪk/", "n. 头痛", "12", False),
    ("hear from", "", "收到……来信", "56", False),
    ("hear of", "", "听说", "62", False),
    ("heartbeat", "/'hɑːtbiːt/", "n. 心跳", "48", False),
    ("heat wave", "", "热浪", "48", False),
    ("help out", "", "帮忙解决困难", "75", False),
    ("hero", "/'hɪərəʊ/", "n. (pl. heroes) 英雄", "47", False),
    ("hidden", "/'hɪdn/", "adj. 隐藏的", "66", False),
    ("hide", "/haɪd/", "v. (hid; hidden) 躲藏", "45", False),
    ("historical", "/hɪ'stɒrɪkl/", "adj. 历史的", "63", False),
    ("hit", "/hɪt/", "v. (hit) 击打 n. 打击", "18", False),
    ("hug", "/hʌɡ/", "v. & n. 拥抱", "52", False),
    ("hurtful", "/'hɜːtfl/", "adj. 伤人的", "22", False),

    # ===== I =====
    ("ice-skate", "/'aɪsskeɪt/", "v. 滑冰", "5", False),
    ("ice skating", "", "滑冰运动", "3", False),
    ("idiom", "/'ɪdiəm/", "n. 习语；成语", "63", False),
    ("illness", "/'ɪlnəs/", "n. 疾病", "14", False),
    ("importantly", "/ɪm'pɔːtntli/", "adv. 重要的是", "9", False),
    ("impression", "/ɪm'preʃn/", "n. 印象", "59", False),
    ("improper", "/ɪm'prɒpə(r)/", "adj. 不适当的", "58", False),
    ("in future", "", "今后", "23", False),
    ("in low spirits", "", "情绪低落", "26", False),
    ("in need", "", "在困难中", "78", False),
    ("in return", "", "作为回报", "4", False),
    ("in time", "", "及时", "68", False),
    ("include", "/ɪn'kluːd/", "v. 包括", "39", False),
    ("Indian", "/'ɪndiən/", "adj. 印度的 n. 印度人", "53", False),
    ("informal", "/ɪn'fɔːml/", "adj. 非正式的", "58", False),
    ("injury", "/'ɪndʒəri/", "n. 伤害；损伤", "14", False),
    ("ink", "/ɪŋk/", "n. 墨水", "4", False),
    ("inspiration", "/ˌɪnspə'reɪʃn/", "n. 灵感", "8", False),
    ("inspire", "/ɪn'spaɪə(r)/", "v. 激励；鼓舞", "69", False),
    ("instructor", "/ɪn'strʌktə(r)/", "n. 教练；讲师", "3", False),
    ("interview", "/'ɪntəvjuː/", "n. & v. 采访；面试", "43", False),
    ("interviewer", "/'ɪntəvjuːə(r)/", "n. 采访者", "73", False),
    ("introduction", "/ˌɪntrə'dʌkʃn/", "n. 介绍", "69", False),
    ("Italian", "/ɪ'tæliən/", "adj. 意大利的 n. 意大利人；意大利语", "6", False),

    # ===== J =====
    ("jeans", "/dʒiːnz/", "n. (pl.) 牛仔裤", "58", False),
    ("joyful", "/'dʒɔɪfl/", "adj. 快乐的", "28", False),

    # ===== K =====
    ("keep ... off", "", "使……不接近", "54", False),
    ("kingdom", "/'kɪŋdəm/", "n. 王国", "63", False),
    ("kiss", "/kɪs/", "v. & n. 亲吻", "52", False),
    ("knife", "/naɪf/", "n. (pl. knives) 刀", "15", False),
    ("knowledge", "/'nɒlɪdʒ/", "n. 知识", "47", False),
    ("kung fu", "/ˌkʌŋ 'fuː/", "n. 功夫", "5", False),

    # ===== L =====
    ("ladder", "/'lædə(r)/", "n. 梯子", "37", False),
    ("lady", "/'leɪdi/", "n. 女士", "76", False),
    ("landslide", "/'lændslaɪd/", "n. 山体滑坡", "48", False),
    ("lastly", "/'lɑːstli/", "adv. 最后", "25", False),
    ("let down", "", "使失望", "26", False),
    ("level", "/'levl/", "n. 水平；级别", "32", False),
    ("librarian", "/laɪ'breəriən/", "n. 图书管理员", "68", False),
    ("lie", "/laɪ/", "v. (lay; lain) 躺；位于", "28", False),
    ("life-saving", "/'laɪfseɪvɪŋ/", "adj. 救生的", "77", False),
    ("lifetime", "/'laɪftaɪm/", "n. 一生；终身", "39", False),
    ("literary", "/'lɪtərəri/", "adj. 文学的", "65", False),
    ("located", "/ləʊ'keɪtɪd/", "adj. 位于", "38", False),
    ("lock", "/lɒk/", "v. 锁上 n. 锁", "66", False),
    ("lock up", "", "锁好；关押", "66", False),
    ("lonely", "/'ləʊnli/", "adj. 孤独的", "22", False),
    ("look on the bright side", "", "看光明的一面", "24", False),
    ("lost", "/lɒst/", "adj. 迷路的；丢失的", "64", False),
    ("luckily", "/'lʌkɪli/", "adv. 幸运地", "17", False),

    # ===== M =====
    ("mad", "/mæd/", "adj. 疯狂的；生气的", "28", False),
    ("madam", "/'mædəm/", "n. 女士；夫人", "79", False),
    ("main", "/meɪn/", "adj. 主要的", "59", False),
    ("make a difference", "", "有影响；起作用", "71", False),
    ("make preparations", "", "做准备", "44", False),
    ("manage", "/'mænɪdʒ/", "v. 设法做到；管理", "4", False),
    ("manner", "/'mænə(r)/", "n. (pl. manners) 礼貌；举止", "54", False),
    ("manpower", "/'mænpaʊə(r)/", "n. 人力", "48", False),
    ("married", "/'mærid/", "adj. 已婚的", "56", False),
    ("marry", "/'mæri/", "v. 结婚", "58", False),
    ("mask", "/mɑːsk/", "n. 面具；口罩", "14", False),
    ("mean", "/miːn/", "adj. 刻薄的", "28", False),
    ("measure", "/'meʒə(r)/", "v. 测量 n. 措施", "37", False),
    ("measurement", "/'meʒəmənt/", "n. 测量", "32", False),
    ("medicine", "/'medsn/", "n. 药", "14", False),
    ("merci", "", "(法语) 谢谢", "57", False),
    ("mile", "/maɪl/", "n. 英里", "35", False),
    ("missing", "/'mɪsɪŋ/", "adj. 失踪的", "76", False),
    ("most of all", "", "最重要的是", "77", False),
    ("mystery", "/'mɪstri/", "n. 神秘的事物", "62", False),

    # ===== N =====
    ("namaste", "/nɑː'mɑːsteɪ/", "interj. (印度)合十礼", "53", False),
    ("natural", "/'nætʃrəl/", "adj. 自然的", "38", False),
    ("naughty", "/'nɔːti/", "adj. 淘气的", "68", False),
    ("nearby", "/ˌnɪə'baɪ/", "adj. 附近的 adv. 在附近", "46", False),
    ("nearly", "/'nɪəli/", "adv. 几乎；将近", "43", False),
    ("negative", "/'neɡətɪv/", "adj. 消极的；负面的", "28", False),
    ("neighbourhood", "/'neɪbəhʊd/", "n. (= neighborhood) 街区", "43", False),
    ("nervously", "/'nɜːvəsli/", "adv. 紧张地", "19", False),
    ("nicely", "/'naɪsli/", "adv. 很好地", "56", False),
    ("no way", "", "不可能；没门", "16", False),
    ("nobody", "/'nəʊbədi/", "pron. 没有人", "66", False),
    ("normal", "/'nɔːml/", "adj. 正常的", "28", False),
    ("northeastern", "/ˌnɔːθ'iːstən/", "adj. 东北的", "39", False),
    ("northern", "/'nɔːðən/", "adj. 北方的", "36", False),
    ("nosebleed", "/'nəʊzbliːd/", "n. 鼻出血", "13", False),
    ("not only ... but also ...", "", "不仅……而且……", "29", False),
    ("nursing home", "", "养老院", "74", False),

    # ===== O =====
    ("object", "/'ɒbdʒɪkt/", "n. 物体；目标", "6", False),
    ("occasion", "/ə'keɪʒn/", "n. 场合", "56", False),
    ("old-fashioned", "/ˌəʊld 'fæʃnd/", "adj. 过时的", "7", False),
    ("on fire", "", "着火", "16", False),
    ("on purpose", "", "故意地", "25", False),
    ("on the go", "", "忙碌；在活动中", "78", False),
    ("on top of the world", "", "欣喜若狂", "26", False),
    ("once in a while", "", "偶尔", "5", False),
    ("onto", "/'ɒntu; 'ɒntə/", "prep. 到……上", "16", False),
    ("ordinary", "/'ɔːdnri/", "adj. 普通的", "77", False),
    ("organization", "/ˌɔːɡənaɪ'zeɪʃn/", "n. (= organisation) 组织", "72", False),
    ("ourselves", "/aʊə'selvz; ɑː'selvz/", "pron. 我们自己", "11", False),
    ("out of breath", "", "上气不接下气", "49", False),
    ("outing", "/'aʊtɪŋ/", "n. 郊游；外出", "5", False),
    ("owner", "/'əʊnə(r)/", "n. 所有者", "73", False),

    # ===== P =====
    ("pain", "/peɪn/", "n. 疼痛", "15", False),
    ("painful", "/'peɪnfl/", "adj. 痛苦的", "66", False),
    ("palm", "/pɑːm/", "n. 手掌", "53", False),
    ("panic", "/'pænɪk/", "n. 恐慌", "16", False),
    ("pass away", "", "去世", "29", False),
    ("patient", "/'peɪʃnt/", "n. 病人 adj. 耐心的", "14", False),
    ("peanut", "/'piːnʌt/", "n. 花生", "19", False),
    ("physics", "/'fɪzɪks/", "n. 物理(学)", "28", False),
    ("pill", "/pɪl/", "n. 药丸", "18", False),
    ("player", "/'pleɪə(r)/", "n. 运动员；玩家", "26", False),
    ("plenty", "/'plenti/", "pron. 大量；充足", "25", False),
    ("plenty of", "", "大量的", "25", False),
    ("pocket", "/'pɒkɪt/", "n. 口袋", "78", False),
    ("pocket money", "", "零花钱", "78", False),
    ("poem", "/'pəʊɪm/", "n. 诗", "4", False),
    ("pool", "/puːl/", "n. 水池；游泳池", "35", False),
    ("postcard", "/'pəʊstkɑːd/", "n. 明信片", "6", False),
    ("power", "/'paʊə(r)/", "n. 力量；权力", "45", False),
    ("practical", "/'præktɪkl/", "adj. 实用的", "77", False),
    ("preparation", "/ˌprepə'reɪʃn/", "n. 准备", "44", False),
    ("present", "/'preznt/", "n. 礼物", "23", False),
    ("press", "/pres/", "v. 按；压", "13", False),
    ("pressure", "/'preʃə(r)/", "n. 压力", "24", False),
    ("primary", "/'praɪməri/", "adj. 初级的；主要的", "75", False),
    ("private", "/'praɪvət/", "adj. 私人的；私密的", "56", False),
    ("program", "/'prəʊɡræm/", "v. 编程 n. (= programme) 节目；程序", "2", False),
    ("programmer", "/'prəʊɡræmə(r)/", "n. 程序员", "6", False),
    ("proper", "/'prɒpə(r)/", "adj. 适当的", "54", False),
    ("proud", "/praʊd/", "adj. 自豪的", "26", False),
    ("proud of", "", "为……自豪", "26", False),
    ("prove", "/pruːv/", "v. 证明", "66", False),
    ("provide", "/prə'vaɪd/", "v. 提供", "72", False),
    ("pull together", "", "齐心协力", "26", False),
    ("punish", "/'pʌnɪʃ/", "v. 惩罚", "63", False),
    ("purpose", "/'pɜːpəs/", "n. 目的", "25", False),
    ("push", "/pʊʃ/", "v. 推 n. 推", "5", False),
    ("put oneself in sb's shoes", "", "设身处地为某人着想", "25", False),

    # ===== Q =====
    ("quick", "/kwɪk/", "adj. 快的 adv. 快地", "16", False),

    # ===== R =====
    ("rainstorm", "/'reɪnstɔːm/", "n. 暴雨", "49", False),
    ("rather", "/'rɑːðə(r)/", "adv. 相当；宁愿", "7", False),
    ("reader", "/'riːdə(r)/", "n. 读者", "68", False),
    ("receive", "/rɪ'siːv/", "v. 收到；接到", "59", False),
    ("recently", "/'riːsntli/", "adv. 最近", "64", False),
    ("recommend", "/ˌrekə'mend/", "v. 推荐", "65", False),
    ("recommendation", "/ˌrekəmen'deɪʃn/", "n. 推荐", "69", False),
    ("reduce", "/rɪ'djuːs/", "v. 减少", "6", False),
    ("reef", "/riːf/", "n. 礁石", "39", False),
    ("referee", "/ˌrefə'riː/", "n. 裁判", "26", False),
    ("refuse", "/rə'fjuːz/", "v. 拒绝", "46", False),
    ("relative", "/'relətɪv/", "n. 亲戚", "44", False),
    ("relaxed", "/rɪ'lækst/", "adj. 放松的", "28", False),
    ("remain", "/rɪ'meɪn/", "v. 保持；剩余", "29", False),
    ("repeat", "/rɪ'piːt/", "v. 重复", "26", False),
    ("report", "/rɪ'pɔːt/", "n. & v. 报告；报道", "43", False),
    ("rescue", "/'reskjuː/", "n. & v. 救援", "48", False),
    ("return", "/rɪ'tɜːn/", "n. & v. 返回；归还", "4", False),
    ("review", "/rɪ'vjuː/", "v. 复习 n. 评论", "49", False),
    ("ring", "/rɪŋ/", "v. (rang; rung) 打电话；响铃", "26", False),
    ("risk", "/rɪsk/", "v. 冒险 n. 风险", "37", False),
    ("risky", "/'rɪski/", "adj. 有风险的", "38", False),
    ("roll", "/rəʊl/", "v. 滚动；卷", "16", False),
    ("roof", "/ruːf/", "n. 屋顶", "43", False),
    ("rub", "/rʌb/", "v. 摩擦；擦", "52", False),
    ("rude", "/ruːd/", "adj. 粗鲁的", "53", False),
    ("runny", "/'rʌni/", "adj. 流鼻涕的", "13", False),

    # ===== S =====
    ("sadly", "/'sædli/", "adv. 悲伤地", "17", False),
    ("safeguard", "/'seɪfɡɑːd/", "v. 保护", "48", False),
    ("safety", "/'seɪfti/", "n. 安全", "15", False),
    ("sand", "/sænd/", "n. 沙子", "39", False),
    ("scared", "/skeəd/", "adj. 害怕的", "3", False),
    ("scared of", "", "害怕", "3", False),
    ("schoolgirl", "/'skuːlɡɜːl/", "n. 女学生", "46", False),
    ("score", "/skɔː(r)/", "n. 分数 v. 得分", "26", False),
    ("scream", "/skriːm/", "v. 尖叫", "46", False),
    ("sea level", "", "海平面", "32", False),
    ("secondly", "/'sekəndli/", "adv. 第二", "58", False),
    ("secretly", "/'siːkrətli/", "adv. 秘密地", "66", False),
    ("security", "/sɪ'kjʊərəti/", "n. 安全；保安", "46", False),
    ("security guard", "", "保安人员", "46", False),
    ("selfish", "/'selfɪʃ/", "adj. 自私的", "66", False),
    ("serving", "/'sɜːvɪŋ/", "adj. 用于上菜的 n. 一份", "54", False),
    ("serving chopsticks", "", "公筷", "54", False),
    ("shake", "/ʃeɪk/", "v. (shook; shaken) 摇动；握手 n. 摇动", "52", False),
    ("shelter", "/'ʃeltə(r)/", "n. 庇护所", "73", False),
    ("shock", "/ʃɒk/", "n. 震惊 v. 使震惊", "18", False),
    ("shocked", "/ʃɒkt/", "adj. 震惊的", "22", False),
    ("shoulder", "/'ʃəʊldə(r)/", "n. 肩膀", "36", False),
    ("shout at", "", "对……喊叫", "28", False),
    ("shut", "/ʃʌt/", "v. (shut) 关闭", "25", False),
    ("shut away", "", "把……关起来", "25", False),
    ("sign up", "", "报名", "76", False),
    ("sign-off", "/'saɪnɒf/", "n. 结束语", "59", False),
    ("simply", "/'sɪmpli/", "adv. 简单地；仅仅", "37", False),
    ("since", "/sɪns/", "prep., adv. & conj. 自从；既然", "66", False),
    ("single", "/'sɪŋɡl/", "adj. 单个的；单身的", "4", False),
    ("sit up", "", "坐起来", "54", False),
    ("ski", "/skiː/", "v. 滑雪", "2", False),
    ("slow down", "", "减速；放慢", "43", False),
    ("smoke", "/sməʊk/", "n. 烟 v. 吸烟", "17", False),
    ("snowstorm", "/'snəʊstɔːm/", "n. 暴风雪", "42", False),
    ("so far", "", "到目前为止", "8", False),
    ("so that", "", "以便；结果是", "23", False),
    ("society", "/sə'saɪəti/", "n. 社会", "65", False),
    ("soldier", "/'səʊldʒə(r)/", "n. 士兵", "75", False),
    ("solution", "/sə'luːʃn/", "n. 解决方案", "27", False),
    ("sore", "/sɔː(r)/", "adj. 疼痛的", "12", False),
    ("soundly", "/'saʊndli/", "adv. 酣畅地", "45", False),
    ("southern", "/'sʌðən/", "adj. 南方的", "38", False),
    ("southwestern", "/ˌsaʊθ'westən/", "adj. 西南的", "48", False),
    ("spoiled", "/spɔɪld/", "adj. (also spoilt) 宠坏的", "66", False),
    ("square kilometre", "", "平方公里", "32", False),
    ("stadium", "/'steɪdiəm/", "n. 体育场", "72", False),
    ("stage", "/steɪdʒ/", "n. 舞台；阶段", "8", False),
    ("stamp", "/stæmp/", "n. 邮票", "6", False),
    ("standard", "/'stændəd/", "n. 标准", "24", False),
    ("state", "/steɪt/", "n. 状态；州 v. 陈述", "66", False),
    ("steal", "/stiːl/", "v. (stole; stolen) 偷窃", "63", False),
    ("stomach", "/'stʌmək/", "n. 胃；肚子", "13", False),
    ("stomachache", "/'stʌməkeɪk/", "n. 胃痛", "12", False),
    ("stop ... from doing", "", "阻止……做", "14", False),
    ("stop short", "", "突然停下", "16", False),
    ("stove", "/stəʊv/", "n. 炉子", "16", False),
    ("stress", "/stres/", "n. 压力", "6", False),
    ("strict", "/strɪkt/", "adj. 严格的", "8", False),
    ("stroke", "/strəʊk/", "n. 中风", "4", False),
    ("structure", "/'strʌktʃə(r)/", "n. 结构", "39", False),
    ("submersible", "/səb'mɜːsəbl/", "n. 潜水器", "33", False),
    ("success", "/sək'ses/", "n. 成功", "78", False),
    ("successful", "/sək'sesfl/", "adj. 成功的", "77", False),
    ("successfully", "/sək'sesfəli/", "adv. 成功地", "37", False),
    ("sudden", "/'sʌdn/", "adj. 突然的", "49", False),
    ("suffer", "/'sʌfə(r)/", "v. 遭受；忍受", "12", False),
    ("suffer from", "", "遭受；患……病", "12", False),
    ("suggestion", "/sə'dʒestʃən/", "n. 建议", "8", False),
    ("summary", "/'sʌməri/", "n. 摘要；总结", "66", False),
    ("supply", "/sə'plaɪ/", "n. (pl. supplies) 供应 v. 供应", "44", False),
    ("surface", "/'sɜːfɪs/", "n. 表面", "32", False),
    ("surprising", "/sə'praɪzɪŋ/", "adj. 令人惊讶的", "55", False),
    ("surprisingly", "/sə'praɪzɪŋli/", "adv. 惊人地", "8", False),
    ("survive", "/sə'vaɪv/", "v. 幸存；存活", "36", False),

    # ===== T =====
    ("table manners", "", "餐桌礼仪", "54", False),
    ("take a deep breath", "", "深吸一口气", "28", False),
    ("take a seat", "", "坐下", "14", False),
    ("take back", "", "收回", "26", False),
    ("take sb's temperature", "", "给某人量体温", "14", False),
    ("talent", "/'tælənt/", "n. 天赋；才能", "79", False),
    ("teammate", "/'tiːmmeɪt/", "n. 队友", "36", False),
    ("teamwork", "/'tiːmwɜːk/", "n. 团队合作", "77", False),
    ("teenage", "/'tiːneɪdʒ/", "adj. 青少年的", "6", False),
    ("temper", "/'tempə(r)/", "n. 脾气", "41", False),
    ("terribly", "/'terəbli/", "adv. 非常；可怕地", "49", False),
    ("test", "/test/", "n. & v. 测试；检验", "14", False),
    ("thankful", "/'θæŋkfl/", "adj. 感激的", "28", False),
    ("thankfully", "/'θæŋkfəli/", "adv. 幸亏", "47", False),
    ("the elderly", "", "老年人", "72", False),
    ("themselves", "/ðəm'selvz/", "pron. 他们自己", "16", False),
    ("therefore", "/'ðeəfɔː(r)/", "adv. 因此", "66", False),
    ("thick", "/θɪk/", "adj. 厚的；浓的", "45", False),
    ("thinking", "/'θɪŋkɪŋ/", "n. 思考；想法", "47", False),
    ("thirdly", "/'θɜːdli/", "adv. 第三", "58", False),
    ("though", "/ðəʊ/", "conj. 尽管；虽然", "27", False),
    ("throat", "/θrəʊt/", "n. 喉咙", "12", False),
    ("throw", "/θrəʊ/", "v. (threw; thrown) 扔；投 n. 投掷", "16", False),
    ("thunder", "/'θʌndə(r)/", "n. 雷声 v. 打雷", "49", False),
    ("tight", "/taɪt/", "adj. 紧的", "19", False),
    ("tonight", "/tə'naɪt/", "adv. 今晚 n. 今晚", "17", False),
    ("toothache", "/'tuːθeɪk/", "n. 牙痛", "12", False),
    ("tornado", "/tɔː'neɪdəʊ/", "n. 龙卷风", "45", False),
    ("tradition", "/trə'dɪʃn/", "n. 传统", "58", False),
    ("traveller", "/'trævələ(r)/", "n. (= traveler) 旅行者", "38", False),
    ("trouble", "/'trʌbl/", "n. 麻烦 v. 使烦恼", "43", False),
    ("truck", "/trʌk/", "n. 卡车", "44", False),
    ("tsunami", "/tsuː'nɑːmi/", "n. 海啸", "43", False),
    ("turn on", "", "打开（水、电等）", "16", False),
    ("turtle", "/'tɜːtl/", "n. 海龟", "39", False),
    ("type", "/taɪp/", "n. 类型", "38", False),
    ("typhoon", "/taɪ'fuːn/", "n. 台风", "42", False),

    # ===== U =====
    ("uncommon", "/ʌn'kɒmən/", "adj. 不寻常的", "53", False),
    ("underwater", "/ˌʌndə'wɔːtə(r)/", "adj. 水下的 adv. 在水下", "39", False),
    ("unfortunately", "/ʌn'fɔːtʃənətli/", "adv. 不幸地", "46", False),
    ("unless", "/ən'les/", "conj. 除非", "54", False),
    ("unlock", "/ʌn'lɒk/", "v. 解锁；开启", "66", False),
    ("unlucky", "/ʌn'lʌki/", "adj. 不幸的", "49", False),
    ("unsafe", "/ʌn'seɪf/", "adj. 不安全的", "58", False),
    ("unusual", "/ʌn'juːʒuəl/", "adj. 不寻常的", "33", False),
    ("up to", "", "多达；取决于", "4", False),
    ("upset", "/ʌp'set/", "adj. 心烦的", "22", False),
    ("usual", "/'juːʒuəl/", "adj. 通常的", "49", False),

    # ===== V =====
    ("value", "/'væljuː/", "n. 价值", "77", False),
    ("virus", "/'vaɪrəs/", "n. 病毒", "14", False),
    ("visitor", "/'vɪzɪtə(r)/", "n. 访客；游客", "72", False),
    ("voluntary", "/'vɒləntri/", "adj. 自愿的", "77", False),
    ("volunteer", "/ˌvɒlən'tɪə(r)/", "n. 志愿者", "74", False),

    # ===== W =====
    ("wake up", "", "醒来", "28", False),
    ("warmly", "/'wɔːmli/", "adv. 热情地", "75", False),
    ("warn", "/wɔːn/", "v. 警告", "42", False),
    ("waterfall", "/'wɔːtəfɔːl/", "n. 瀑布", "34", False),
    ("wave", "/weɪv/", "n. 波浪 v. 挥手", "43", False),
    ("weak", "/wiːk/", "adj. 虚弱的", "66", False),
    ("what's more", "", "而且；更重要的是", "15", False),
    ("whether", "/'weðə(r)/", "conj. 是否", "56", False),
    ("wildfire", "/'waɪldfaɪə(r)/", "n. 野火", "42", False),
    ("willing", "/'wɪlɪŋ/", "adj. 愿意的", "77", False),
    ("wonder", "/'wʌndə(r)/", "n. 奇迹 v. 想知道", "31", False),
    ("worst", "/wɜːst/", "adj. & adv. (bad/badly的最高级) 最坏的", "46", False),
    ("worth", "/wɜːθ/", "adj. 值得的", "77", False),

    # ===== X =====
    ("X-ray", "/'eksreɪ/", "n. X射线；X光片", "13", False),

    # ===== Y =====
    ("yoga", "/'jəʊɡə/", "n. 瑜伽", "6", False),
    ("youth", "/juːθ/", "n. 青年；青春", "74", False),
]

def generate_md(vocab, title, output_path):
    lines = [f"# {title}\n"]
    lines.append("> 注：加 `*` 的词为《义务教育英语课程标准（2022年版）》中的二级词。\n")
    lines.append("---\n")
    import string
    for letter in string.ascii_uppercase:
        group = [(w, p, c, pg, k) for w, p, c, pg, k in vocab
                 if w.lstrip('*').upper().startswith(letter)]
        if group:
            lines.append(f"## {letter}\n")
            lines.append("| 单词 | 音标 | 释义 | 页码 |")
            lines.append("|------|------|------|------|")
            for w, p, c, pg, k in group:
                phonetic = p if p else ""
                lines.append(f"| {w} | {phonetic} | {c} | p. {pg} |")
            lines.append("")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return len(vocab)

out = os.path.join(BASE, '八年级下册词汇表.md')
n = generate_md(C2B_VOCAB, "人教版 PEP 八年级下册词汇表", out)
key_count = sum(1 for _,_,_,_,k in C2B_VOCAB if k)
print(f"Generated: {out}")
print(f"Total: {n} entries (key: {key_count}, non-key: {n - key_count})")